// questions.js - بنك الأسئلة والمقررات الكامل بدون أي اختصار
const COURSES_DATA = {
  // ==========================================
  // المقرر الأول: AR111 (381 سؤالاً كاملاً)
  // ==========================================
  ar111: {
    id: "ar111",
    title: "AR111 - المهارات اللغوية",
    desc: "بنك تجميعات الميدتيرم والكويز الشامل (381 سؤالاً)",
    icon: "📖",
    color: "indigo",
    sources: [
      {
        name: "AR111_المراجعة_الشاملة_مع_الحلول_الميد_والكويز_نايف.pdf",
        author: "إعداد: نايف بن عبد العزيز",
        details: "نسخة (١) مراجعة شاملة لأسئلة الميدتيرم والكويز (1) تحتوي على 381 سؤالاً",
        url: "fils/AR111/AR111-Review.pdf"
      }
    ],
    questions: [
      { id: 1, q: "علامة رفع الأسماء الخمسة:", opts: ["الضمة", "الواو", "الألف", "ثبوت النون"], c: 1, exp: "ترفع الأسماء الخمسة بالواو (مثل: جاء أبوك)." },
      { id: 2, q: "الاسم المعرب من التالي:", opts: ["الذين", "الذي", "اللتان", "اللاتي"], c: 2, exp: "الأسماء الموصولة مبنية ما عدا مثناها (اللذان واللتان) فإنهما يعربان إعراب المثنى." },
      { id: 3, q: "الأمر منها والماضي دائماً مبني:", opts: ["الصفات", "الأسماء", "الأفعال", "الحروف"], c: 2, exp: "الفعل الماضي وفعل الأمر مبنيان دائماً." },
      { id: 4, q: "ما دل على ذات تدرك بالحواس أو بالعقل:", opts: ["الاسم", "الفعل", "الجملة", "الحرف"], c: 0, exp: "الاسم هو ما دل على ذات أو معنى مجرد من الزمان." },
      { id: 5, q: "يتميز الموهوبين بالفطنة والذكاء. العبارة السابقة:", opts: ["صح", "خطأ"], c: 1, exp: "خطأ؛ التصحيح: (الموهوبون) لأنها فاعل مرفوع وعلامة رفعه الواو لأنه جمع مذكر سالم." },
      { id: 6, q: "المعيار الذي يتفاضل فيه الناس عند الله هو المال والنسب:", opts: ["صح", "خطأ"], c: 1, exp: "خطأ؛ المعيار هو التقوى (إن أكرمكم عند الله أتقاكم)." },
      { id: 7, q: "العلامة الاسمية التي في كلمة (الرجل) هي:", opts: ["النداء", "ال التعريف", "الجر", "التنوين"], c: 1, exp: "دخول (ال) التعريف من علامات الأسماء." },
      { id: 8, q: "الفعل المضارع في قولنا (لن تذهب اليوم) منصوب وعلامة نصبه:", opts: ["حذف النون", "الضمة", "الفتحة المقدرة", "الفتحة الظاهرة"], c: 3, exp: "منصوب بالفتحة الظاهرة على آخره لأنه صحيح الآخر مسبوق بـ لن." },
      { id: 9, q: "علامة إعراب جمع المؤنث السالم في حالة النصب:", opts: ["الكسرة وهي أصلية", "الكسرة وهي فرعية", "الفتحة وهي أصلية", "الفتحة وهي فرعية"], c: 1, exp: "ينصب بالكسرة نيابة عن الفتحة، فتعتبر هنا علامة إعراب فرعية." },
      { id: 10, q: "لغة الرسالة الرسمية (اللغة الموضوعية):", opts: ["صح", "خطأ"], c: 0, exp: "الرسائل الرسمية تعتمد على اللغة الموضوعية المباشرة الخالية من العواطف والمبالغات." },
      { id: 11, q: "الفعل المضارع معرب إلا إذا اتصلت به إحدى نوني التوكيد أو نون النسوة:", opts: ["صح", "خطأ"], c: 0, exp: "يبنى المضارع مع نون التوكيد على الفتح، ومع نون النسوة على السكون." },
      { id: 12, q: "علامة رفع المثنى:", opts: ["السكون", "الألف", "الفتحة", "الضمة"], c: 1, exp: "يرفع المثنى بالألف وينصب ويجر بالياء." },
      { id: 13, q: "علامة بناء (حيث) السكون:", opts: ["صح", "خطأ"], c: 1, exp: "خطأ؛ (حيثُ) ظرف مبني على الضم في محل نصب." },
      { id: 14, q: "يعرب المثنى بعلامة إعراب فرعية:", opts: ["صح", "خطأ"], c: 0, exp: "صح؛ لأن علاماته الحروف (الألف رفعاً والياء نصباً وجراً)." },
      { id: 15, q: "من علامات الإعراب الفرعية:", opts: ["الميم", "الضمة", "الياء", "السكون"], c: 2, exp: "الياء علامة فرعية للنصب والجر في المثنى وجمع المذكر السالم." },
      { id: 16, q: "من مميزات الرسائل الديوانية، اعتماد اللغة الموضوعية والإيجاز غير المخل:", opts: ["صح", "خطأ"], c: 0, exp: "الإيجاز واللغة الموضوعية من أبرز خصائص الرسائل الديوانية والإدارية." },
      { id: 17, q: "لن يرقى الكسول إلى المجد، الفعل المضارع هنا:", opts: ["فعل مضارع منصوب بالفتحة الظاهرة", "فعل مضارع منصوب بالفتحة المقدرة", "فعل مضارع مرفوع", "فعل مضارع مجزوم"], c: 1, exp: "منصوب بفتحة مقدرة على الألف منع من ظهورها التعذر." },
      { id: 18, q: "أقسام الكلام:", opts: ["حرف", "اسم", "فعل", "حرف واسم وفعل"], c: 3, exp: "الكلام العربي ينقسم إلى ثلاثة أقسام: اسم وفعل وحرف." },
      { id: 19, q: "من مميزات الاسم التنوين:", opts: ["صح", "خطأ"], c: 0, exp: "التنوين من خصائص وعلامات الاسم المميزة له عن الفعل والحرف." },
      { id: 20, q: "(هذا أبوك) أبوك تعرب:", opts: ["اسم مرفوع وعلامة رفعه الضمة الظاهرة", "اسم مجرور وعلامة جره الياء", "اسم منصوب وعلامة نصبه الألف", "اسم مرفوع وعلامة رفعه الواو لأنه من الأسماء الخمسة"], c: 3, exp: "خبر مرفوع وعلامة رفعه الواو لأنه من الأسماء الخمسة." },
      { id: 21, q: "ليفوزَنَّ المجتهد، الفعل المضارع هنا معرب:", opts: ["صح", "خطأ"], c: 1, exp: "خطأ؛ مبني على الفتح لاتصاله اتصالاً مباشراً بنون التوكيد الثقيلة." },
      { id: 22, q: "ما الاسم مما يلي تكون علامة إعرابه فرعية:", opts: ["أبوك", "خالد", "أنت", "محمد"], c: 0, exp: "أبوك من الأسماء الخمسة ويعرب بالحروف (علامات فرعية)." },
      { id: 23, q: "ما كان دالاً على الحدث مقترناً بزمن:", opts: ["الجملة", "الحرف", "الفعل", "الاسم"], c: 2, exp: "الفعل يدل على حدث وزمن، بينما الاسم يدل على حدث مجرد من الزمان." },
      { id: 24, q: "علامة نصب الأسماء الخمسة هي الواو:", opts: ["صح", "خطأ"], c: 1, exp: "خطأ؛ تنصب الأسماء الخمسة بالألف (رأيت أباك)." },
      { id: 25, q: "كلمة مجردة من الزمن:", opts: ["الفعل الماضي", "الفعل المضارع", "الاسم", "الفعل الأمر"], c: 2, exp: "الاسم يدل على المعنى أو الذات دون اقتران بزمن." },
      { id: 26, q: "تكتب (دفء) بعد اتصال ألف التنوين بها:", opts: ["دفنا", "دفا", "دفء", "دفئاً"], c: 3, exp: "تكتب (دفئاً) لأن الفاء تقبل الاتصال بما بعدها فترسم على نبرة." },
      { id: 27, q: "الأفعال: (يكتبون، يكتبان، تكتبين) من الأسماء الخمسة:", opts: ["صح", "خطأ"], c: 1, exp: "خطأ؛ هي من الأفعال الخمسة وليست من الأسماء." },
      { id: 28, q: "الفعل المبني من الكلمات الآتية:", opts: ["غافر", "غَفَرَ", "يغفرون", "يغفر"], c: 1, exp: "(غفر) فعل ماضٍ، والفعل الماضي مبني دائماً." },
      { id: 29, q: "(في، على، إلى، من، عن) هذه الحروف تختص بالأسماء فقط:", opts: ["صح", "خطأ"], c: 0, exp: "صح؛ لأنها حروف جر ولا تدخل إلا على الأسماء." },
      { id: 30, q: "في قوله: (أحبب به ثوباً) أسلوب إنشائي تعجبي:", opts: ["صح", "خطأ"], c: 0, exp: "صيغة (أَفْعِلْ به) من صيغ التعجب القياسية الإنشائية." },
      { id: 31, q: "في قوله (وما الحب إلا طاعة) استعمل الشاعر أسلوب:", opts: ["أسلوب قصر", "أسلوب تعجب", "أسلوب إطناب", "أسلوب خبري"], c: 0, exp: "أسلوب قصر بالنفي (ما) والاستثناء (إلا)." },
      { id: 32, q: "مررت بينبعَ في طريق السفر. علامة ينبع الإعرابية تجر بالفتحة:", opts: ["صح", "خطأ"], c: 0, exp: "صح؛ ممنوع من الصرف للعلمية ووزن الفعل فيجر بالفتحة نيابة عن الكسرة." },
      { id: 33, q: "من الأسماء الخمسة المعربة بالعلامات الفرعية:", opts: ["إخوان", "أخ", "أخوك", "أخي"], c: 2, exp: "أخوك لأنها مفردة ومضافة لغير ياء المتكلم. (أخي تعرب بحركات مقدرة)." },
      { id: 34, q: "(حيث، أمس) ظرفان معربان:", opts: ["صح", "خطأ"], c: 1, exp: "خطأ؛ حيث وأمس ظرفان مبنيان (حيثُ على الضم، وأمسِ على الكسر)." },
      { id: 35, q: "جملة (لم يسعَ أخوك في طلب رزقه)، (يسع) فعل مضارع مجزوم وعلامة جزمه:", opts: ["الفتحة", "السكون", "حذف النون", "حذف حرف العلة"], c: 3, exp: "حذف حرف العلة (الألف) والفتحة دليل عليها." },
      { id: 36, q: "الحروف كلها معربة:", opts: ["صح", "خطأ"], c: 1, exp: "خطأ؛ جميع الحروف مبنية لا محل لها من الإعراب." },
      { id: 37, q: "من الأسماء الملحقة بجمع المذكر السالم:", opts: ["عشر", "عشرون", "أحد عشر", "خمسة عشر"], c: 1, exp: "عشرون من ألفاظ العقود الملحقة بجمع المذكر السالم." },
      { id: 38, q: "هي كل فعل مضارع اتصل بألف الاثنين أو واو الجماعة أو ياء المؤنثة المخاطبة:", opts: ["الأفعال المعتلة", "الأفعال الناسخة", "أفعال القلوب", "الأفعال الخمسة"], c: 3, exp: "هذا هو التعريف النحوي الدقيق للأفعال الخمسة." },
      { id: 39, q: "كلمة (عليون) من ملحقات جمع المذكر السالم:", opts: ["صح", "خطأ"], c: 0, exp: "عليون وأهلون وسنون وبنون من ملحقات جمع المذكر السالم." },
      { id: 40, q: "يرفع المثنى بالكسرة وينصب بالفتحة ويجر بالكسرة:", opts: ["صح", "خطأ"], c: 1, exp: "خطأ؛ يرفع بالألف وينصب ويجر بالياء." },
      { id: 41, q: "الاسم لا يتم معناه إلا مع حرف:", opts: ["صح", "خطأ"], c: 1, exp: "خطأ؛ هذا تعريف الحرف، أما الاسم فله معنى تام ومستقل في ذاته." },
      { id: 42, q: "حذفت التاء في الفعل (تنابزوا) للتخفيف ودفع الثقل:", opts: ["صح", "خطأ"], c: 0, exp: "حذفت إحدى التاءين في (تتنابزوا) لدفع ثقل توالي حرفين متماثلين." },
      { id: 43, q: "من علامات الإعراب الأصلية:", opts: ["الألف", "الضمة", "الياء", "الواو"], c: 1, exp: "الضمة علامة رفع أصلية، أما البقية ففرعية." },
      { id: 44, q: "المعنى في (وَلَا تَلْمِزُوا أَنفُسَكُمْ):", opts: ["لا يعب بعضكم بعضاً", "لا تداعوا بالأسئلة المكروهة", "تتبع أحدكم عورات الآخرين", "لا يذكر أحدكم الآخر بما يكره"], c: 0, exp: "اللمز هو العيب، أي لا يعب بعضكم بعضاً لأن المؤمنين كنفس واحدة." },
      { id: 45, q: "من العلامات الإعرابية الأصلية: الكسرة في حالة النصب:", opts: ["صح", "خطأ"], c: 1, exp: "خطأ؛ الكسرة في النصب علامة فرعية (خاصة بجمع المؤنث السالم)." },
      { id: 46, q: "الاسم الموصول (اللذان) يعرب إعراب المثنى:", opts: ["صح", "خطأ"], c: 0, exp: "صح؛ اللذان واللتان يلحقان بإعراب المثنى بالألف والياء." },
      { id: 47, q: "الممنوع من الصرف من الكلمات التالية:", opts: ["المدارس", "سعد", "أحمد", "القبائل"], c: 2, exp: "أحمد ممنوع من الصرف للعلمية ووزن الفعل (المدارس معرفة بـ أل فتصرف)." },
      { id: 48, q: "كلمة (نبوءة) مكتوبة بشكل صحيح:", opts: ["صح", "خطأ"], c: 0, exp: "صح؛ الهمزة المفتوحة بعد واو مد ساكنة ترسم مفردة على السطر." },
      { id: 49, q: "تعد الكلمات التالية (الناجحون، المفلحون، المصلحون):", opts: ["جمع المؤنث السالم", "جمع المذكر السالم", "جمع تكسير", "عدد مركب"], c: 1, exp: "جمع مذكر سالم ينتهي بالواو والنون الزائدتين في الرفع." },
      { id: 50, q: "من علامات الفعل المضارع اتصاله بنون النسوة:", opts: ["صح", "خطأ"], c: 0, exp: "صح؛ يقبل نون النسوة (يكتبن) ونوني التوكيد و(لم ولن)." }
    ]
  },

  // ==========================================
  // المقرر الثاني: TU170 (136 سؤالاً شاملاً)
  // ==========================================
  tu170: {
    id: "tu170",
    title: "TU170 - الحوسبة الأساسية وتكنولوجيا المعلومات",
    desc: "بنك تجميعات الميدتيرم، الكويزات، والفاينل للجامعة العربية المفتوحة (136 سؤالاً)",
    icon: "💻",
    color: "blue",
    sources: [
      {
        name: "TU170-Questions - 2025 - Final.pdf",
        author: "إعداد: أبو طلال",
        details: "تجميعات أسئلة الفاينل الشاملة مع ملف 2",
        url: "fils/TU170/4_5976611103084389520.pdf"
      },
      {
        name: "TU170MTA - اختبار منتصف الفصل (Attempt Review).pdf",
        author: "نظام الاختبارات Olexam",
        details: "أسئلة الميدتيرم الكاملة مع توثيق الإجابات النموذجية",
        url: "fils/TU170/MTA.pdf"
      },
      {
        name: "أسئلة الميد TU170.pdf",
        author: "إعداد: إبراهيم محمد / أعضاء دوافير",
        details: "شاملة الاجتماعات 1 و 2 و 3 (Meetings 1, 2, 3)",
        url: "fils/TU170/أسألة الميد TU170 (نسخة الجوال).pdf"
      },
      {
         name: "",
        author: "",
        details: "",
        url:"fils/TU170/تجميعة الدوافير ميد TU170.pdf"
      }
    ],
    questions: [
      { id: 1, q: "What is a file in a computer system?", opts: ["A storage device", "A collection of program instructions or data stored as a single unit", "A collection of folders", "A software application"], c: 1, exp: "A file is a collection of program instructions or data stored as a single unit." },
      { id: 2, q: "One of the following is NOT a feature of an embedded computer:", opts: ["Often used in businesses that manage large amounts of data", "A specially designed computer chip that resides in another device", "Typically does not receive input from the user", "A self-contained computer device with its own programming"], c: 0, exp: "Mainframes are the computers used in businesses managing large amounts of data, not embedded computers." },
      { id: 3, q: "How do computer viruses mainly spread?", opts: ["When people open infected files", "By taking advantage of weak security", "By using secret codes to hide", "By spreading automatically over networks"], c: 0, exp: "Computer viruses mainly spread when users open or execute infected files." },
      { id: 4, q: "What do you call a procrastinator who tends to take on too many commitments to avoid disappointing others?", opts: ["Worrier", "Crisis Maker", "Dreamer", "Overdoer"], c: 3, exp: "An Overdoer takes on too much work and commitments to avoid disappointing others." },
      { id: 5, q: "iCloud is an example of:", opts: ["Email address", "Search engine", "File storage service", "Web browser"], c: 2, exp: "iCloud is a cloud file storage and backup service by Apple." },
      { id: 6, q: "To protect your computer from viruses you need to:", opts: ["Keep your operating system up to date", "All answers are correct", "Use a secure network", "Install antivirus software"], c: 1, exp: "All of these practices contribute to system security against viruses." },
      { id: 7, q: "A ______ is a portable computer that has a keyboard, monitor, and other devices integrated into a single compact case.", opts: ["Desktop", "Laptop", "Portable book", "Book"], c: 1, exp: "A laptop is a portable computer integrating input, display, and processing components." },
      { id: 8, q: "E-commerce is the process of storing files and programs online.", opts: ["True", "False"], c: 1, exp: "False; Cloud storage is storing files online, while E-commerce is buying and selling goods online." },
      { id: 9, q: "It is advisable to leave your phone on and easily accessible during lectures for notifications.", opts: ["True", "False"], c: 1, exp: "False; Phones should be muted or turned off during lectures to avoid electronic distraction." },
      { id: 10, q: "Which of the following is the typical Top-Level Domain (TLD) used by networking organizations?", opts: [".edu", ".gov", ".mil", ".net"], c: 3, exp: ".net is traditionally intended for network organizations and providers." },
      { id: 11, q: "A file with the name 'aFile.docx' represents a word processing document.", opts: ["True", "False"], c: 0, exp: "True; .docx is the default file extension for Microsoft Word documents." },
      { id: 12, q: "In binary language every letter on the keyboard is represented by a number of bits.", opts: ["True", "False"], c: 0, exp: "True; Characters are typically represented by 8 bits (1 byte) in ASCII." },
      { id: 13, q: "A program must be loaded into RAM before it can run.", opts: ["True", "False"], c: 0, exp: "True; Programs must be loaded into RAM (Random Access Memory) for the CPU to execute them." },
      { id: 14, q: "The RTOS is also known as:", opts: ["EDS", "Real-time embedded OS", "Control system OS", "Embedded systems"], c: 1, exp: "RTOS stands for Real-Time Operating System, often an embedded OS." },
      { id: 15, q: "______ is the set of instructions that tell the computer how to do its work.", opts: ["Software", "Hardware", "Memory", "Manual"], c: 0, exp: "Software refers to programs and instructions directing computer hardware." },
      { id: 16, q: "If a student spends 10 hours in class each week, how many hours should they dedicate to studying each week?", opts: ["20 to 30 hours", "30 to 42 hours", "20 to 24 hours", "24 to 30 hours"], c: 0, exp: "The general guideline recommends 2 to 3 hours of self-study per lecture hour (10 × 2-3 = 20-30 hrs)." },
      { id: 17, q: "The software that is used to create and edit documents is:", opts: ["Presentation software", "Spreadsheet software", "Database software", "Word processing software"], c: 3, exp: "Word processing software (e.g., Microsoft Word) is used to create text documents." },
      { id: 18, q: "One of the following is NOT a specification of solid-state drives (SSDs):", opts: ["SSDs require little power", "SSDs are not efficient", "SSDs have no moving parts", "SSDs run without noise"], c: 1, exp: "SSDs are highly efficient, have no moving parts, and run silently." },
      { id: 19, q: "What distinguishes a Wide Area Network (WAN) from other types of networks?", opts: ["It is meant for connecting peripherals", "It covers larger geographic areas", "It connects computers within one country only", "It is used for personal devices only"], c: 1, exp: "WAN covers broad geographical areas (e.g., across cities, countries, or globally)." },
      { id: 20, q: "The software that a computer can NOT operate without is the:", opts: ["Application program", "Operating system", "Utility program", "Word processing program"], c: 1, exp: "The operating system controls hardware and coordinates all system operations." },
      { id: 21, q: "One kilobyte (KB) = 1024 bytes.", opts: ["True", "False"], c: 0, exp: "True; 1 KB = 1024 Bytes." },
      { id: 22, q: "A Windows utility program that removes unnecessary files from a hard drive is:", opts: ["Norton Antivirus", "Task Manager", "Disk Cleanup", "Disk Defragmenter"], c: 2, exp: "Disk Cleanup removes temporary and unnecessary files to free storage." },
      { id: 23, q: "Android operating system is not a Microsoft product.", opts: ["True", "False"], c: 0, exp: "True; Android is developed by Google." },
      { id: 24, q: "Which of the following is the most popular web browser?", opts: ["Firefox", "Microsoft Edge", "Safari", "Google Chrome"], c: 3, exp: "Google Chrome is the most widely used web browser globally." },
      { id: 25, q: "Smartphones consist of the following component(s):", opts: ["Memory", "Input and output devices", "Processor", "All answers are correct"], c: 3, exp: "Smartphones are miniature computers with processors, memory, and I/O units." },
      { id: 26, q: "Type of computers that is used in weather forecasting models and systems:", opts: ["Workstation", "Mainframes", "Supercomputers", "Embedded computers"], c: 2, exp: "Supercomputers perform trillions of calculations required for meteorological models." },
      { id: 27, q: "In traditional databases, the table is:", opts: ["A group of related fields", "A group of related records", "None of the answers", "A data category"], c: 1, exp: "A database table is composed of rows/records representing entities." },
      { id: 28, q: "What type of spyware specifically monitors keystrokes?", opts: ["Ransomware", "Adware", "Trojan horse", "Keystroke logger"], c: 3, exp: "A keylogger records user keystrokes to steal passwords and sensitive data." },
      { id: 29, q: "In a wireless network, when is a cable still required?", opts: ["When devices are close to each other", "When using mobile hotspots", "To connect laptops to the Wi-Fi", "To connect the wireless router to the network"], c: 3, exp: "A physical cable connects the wireless router/modem to the ISP or network backbone." },
      { id: 30, q: "What is the primary role of the CPU in a computer?", opts: ["Displaying images", "Storing information permanently", "Processing instructions", "Controlling internet connections"], c: 2, exp: "The Central Processing Unit (CPU) executes software instructions and calculations." },
      { id: 31, q: "Leaving a job because it introduces new technology that you're unfamiliar with is an example of:", opts: ["Staying without adjusting skills", "Quitting from the situation", "Adapting old skills to new demands", "Modifying skills to get by"], c: 1, exp: "Leaving or avoiding the environment represents quitting from the situation." },
      { id: 32, q: "Using syllabi helps in planning effectively for the semester.", opts: ["True", "False"], c: 0, exp: "True; Course syllabi outline deadlines, readings, and assignment dates." },
      { id: 33, q: "How should you organize your day?", opts: ["Around what moves you closer to your goal", "With flexibility", "All answers are correct", "Around entertainments"], c: 0, exp: "Prioritize activities that align with your primary goals and objectives." },
      { id: 34, q: "Considering Bloom's Taxonomy, recalling the key points of a topic is related to the 'Understanding' level.", opts: ["True", "False"], c: 1, exp: "False; Recalling facts belongs to the 'Remembering' level." },
      { id: 35, q: "What is recommended for summarizing class work effectively?", opts: ["Summarizing weekly", "Summarizing before exams only", "Summarizing daily", "Summarizing when you have time"], c: 2, exp: "Daily summarization consolidates memory and prevents exam backlog." },
      { id: 36, q: "Using phishing filters can help protect against online scams.", opts: ["True", "False"], c: 0, exp: "True; Phishing filters detect fraudulent websites and warn users." },
      { id: 37, q: "Critical thinking allows us to evaluate facts before making decisions.", opts: ["True", "False"], c: 0, exp: "True; Critical thinking relies on evidence, facts, and logical deduction." },
      { id: 38, q: "Networking enables multiple devices to share an Internet connection.", opts: ["True", "False"], c: 0, exp: "True; Routers and LANs allow shared internet and printer access." },
      { id: 39, q: "Which group typically benefits from the information collected by cookies?", opts: ["Email service providers", "Consumers directly", "Website owners and companies", "Internet access providers"], c: 2, exp: "Cookies allow website owners to track preferences, analytics, and targeted ads." },
      { id: 40, q: "How do virtual language instructors assist in learning?", opts: ["Provide only written lessons", "Teach only vocabulary", "Correct grammar and suggest new words", "Conduct exams only"], c: 2, exp: "AI-powered language tutors offer real-time feedback, grammar correction, and word usage." },
      { id: 41, q: "Microsoft 365 is an example of commercial application software.", opts: ["True", "False"], c: 0, exp: "True; Microsoft 365 is proprietary commercial productivity software." },
      { id: 42, q: "Fatima struggles in English class because she is messaging friends on her phone. This is:", opts: ["Emotional distraction", "Electronic distraction", "Cultural distraction", "Physical distraction"], c: 1, exp: "Using digital devices inappropriately during class is an electronic distraction." },
      { id: 43, q: "Which of the following statements is NOT correct regarding intellectual property?", opts: ["The increased use of electronic media has made enforcing copyright laws easier", "Intellectual property is protected by copyright laws, patents, and trademarks", "Intellectual property is the result of someone's creativity and knowledge", "All answers"], c: 0, exp: "Electronic media and internet distribution make copyright enforcement more difficult, not easier." },
      { id: 44, q: "The way our body responds to external and internal pressure is known as:", opts: ["Disorganization", "Stress", "Self-management", "Prioritization"], c: 1, exp: "Stress is the body's physical and psychological response to pressures." },
      { id: 45, q: "One of the following is an example of a utility program:", opts: ["User Interface", "Norton Antivirus", "Safari Browser", "None of these"], c: 1, exp: "Antivirus software is classified as a system utility program." },
      { id: 46, q: "What does the file extension .jpg represent?", opts: ["A text file", "An image file", "A video file", "An audio file"], c: 1, exp: ".jpg/.jpeg indicates compressed image files." },
      { id: 47, q: "A specially designed computer chip that resides in another device is a/an:", opts: ["Mainframe", "Workstation", "Embedded computer", "Supercomputer"], c: 2, exp: "An embedded computer is a dedicated microcontroller integrated into appliances, cars, etc." },
      { id: 48, q: "The formal written standards designed to apply to everyone are known as:", opts: ["Ethics", "Property", "Technology", "Laws"], c: 3, exp: "Laws are formal written rules enforced by government institutions." },
      { id: 49, q: "The study of the general nature of morals and moral choices people make is known as:", opts: ["Ethics", "Technology", "Property", "Laws"], c: 0, exp: "Ethics is the philosophical study of moral principles guiding behavior." },
      { id: 50, q: "Which of the following statements is NOT true about P2P networks?", opts: ["All nodes are equal peers", "They rely on direct client/server communication", "They can lead to more efficient use of resources", "Nodes may share resources and data directly"], c: 1, exp: "P2P networks do NOT rely on a centralized client/server architecture." }
    ]
  }
};

// =========================================================================
// الدالة التوسعية لتحميل كامل الـ 381 سؤالاً لـ AR111 والـ 136 لـ TU170
// =========================================================================
(function expandAllDatabases() {
  // 1. توسعة بنك AR111 حتى 381 سؤالاً
  const arList = [
    [51, "كل فعل مضارع اتصل بألف الاثنين أو واو الجماعة أو ياء المخاطبة:", ["الأفعال المعتلة", "الأفعال الخمسة", "أفعال القلوب", "الأفعال الناسخة"], 1, "الأفعال الخمسة."],
    [52, "كتب قصيدة تعبر عن أن الحب قدر يعاني منه المحب طائعاً راضياً:", ["خليل مطران", "أحمد شوقي", "نزار قباني", "المتنبي"], 1, "أمير الشعراء أحمد شوقي في نصه الغزلي العفيف المقرّر."],
    [53, "(لا يغتب) تعني في الآية:", ["لا تذكر أخاك بما يكره", "لا يرحمكم", "لا يعطيكم", "لا يسامحكم"], 0, "الغيبة هي ذكر الأخ في غيبته بما يكره."],
    [54, "من مميزات الرسائل الإخوانية تنويع الأسلوب والإسهاب غير الممل:", ["صح", "خطأ"], 0, "الرسائل الودية والإخوانية تحتمل الإسهاب وتزيين العبارات والعاطفة."],
    [55, "الحروف المشتركة بين الأسماء والأفعال هي حروف:", ["النصب", "الجر", "العطف", "الجزم"], 2, "حروف العطف تدخل على الأسماء والأفعال والجمل، بخلاف الجر (للأسماء) والجزم (للأفعال)."],
    [56, "الرسالة تدخل من ضمن المهارات الكتابية:", ["صح", "خطأ"], 0, "الرسائل بنوعيها تدخل ضمن فنون التعبير والمهارات الكتابية."],
    [57, "الفعل من الكلمات التالية هو:", ["ذهبَ", "الذهب", "الذهاب", "الذاهب"], 0, "(ذهبَ) فعل ماضٍ، أما البقية فأسماء لوجود أل التعريف أو التنوين."],
    [58, "الفعل المضارع من التالي:", ["شرب", "شاربون", "الشرب", "يشرب"], 3, "يشرب مبدوء بأحرف المضارعة ويدل على الحاضر."],
    [59, "يعرب المثنى بعلامات إعراب فرعية:", ["صح", "خطأ"], 0, "صح؛ الألف رفعاً والياء نصباً وجراً."],
    [60, "الحرف لا يتم معناه إلا مع غيره:", ["صح", "خطأ"], 0, "هذا هو التعريف الدقيق للحرف في لغة العرب."],
    [61, "جميع الحروف همزتها همزة قطع ما عدا (ال) التعريف:", ["صح", "خطأ"], 0, "قاعدة إملائية مطردة: جميع الحروف قطع (إن، إلى، أو) إلا التعريف."],
    [62, "من العلامات الإعرابية الأصلية: الكسرة في حالة النصب:", ["صح", "خطأ"], 1, "خطأ؛ علامة فرعية تختص بجمع المؤنث السالم."],
    [63, "يبنى الفعل المضارع على الضم عند اتصاله بنون النسوة:", ["صح", "خطأ"], 1, "خطأ؛ يبنى المضارع على السكون مع نون النسوة (يكتُبْنَ)."],
    [64, "سافر أبوك، (أبوك) اسم مرفوع وعلامة رفعه الضمة الظاهرة:", ["صح", "خطأ"], 1, "خطأ؛ فاعل مرفوع بالواو لأنه من الأسماء الخمسة."],
    [65, "الهمزة المتطرفة تأتي في:", ["آخر الكلمة", "أول الكلمة", "وسط الكلمة", "في أول الحرف"], 0, "الهمزة المتطرفة هي التي تقع في نهاية الكلمة."],
    [66, "الاسم المبني هو الذي لا يتغير شكل آخره بتغير موقعه الإعرابي مثل:", ["المسلمون", "محمد", "مساجد", "هذا"], 3, "(هذا) اسم إشارة مبني يلزم السكون في جميع المواقع."],
    [67, "علامة رفع الاسم في جملة (فاز الصابرون) هي:", ["الضمة", "الواو", "ثبوت النون", "الفتحة"], 1, "الواو لأنه جمع مذكر سالم."],
    [68, "السكون حالة مشتركة بين الأسماء والأفعال:", ["صح", "خطأ"], 1, "خطأ؛ السكون (الجزم) يختص بالأفعال فقط والأسماء لا تُجزم."],
    [69, "ملحق بجمع المذكر السالم (أولو):", ["صح", "خطأ"], 0, "صح؛ (أولو) و(أولي) ملحقة بجمع المذكر السالم."],
    [70, "عسى من له الإحسان يغفر زلتي، الفعل المضارع معرب دائماً:", ["صح", "خطأ"], 1, "خطأ؛ المضارع يعرب ويبنى في حالتين (إذا اتصل بنون النسوة أو التوكيد)."],
    [71, "من الرسائل الإخوانية رسالة لطلب تعديل درجاتك في الجامعة:", ["صح", "خطأ"], 1, "خطأ؛ هذه رسالة إدارية رسمية موجهة لجهة أكاديمية."],
    [72, "الحروف بعضها معرب وبعضها مبني:", ["صح", "خطأ"], 1, "خطأ؛ الحروف كلها مبنية بلا استثناء."],
    [73, "(الكتاب مفيد) العلامة الاسمية في كلمة الكتاب هي (أل):", ["صح", "خطأ"], 0, "صح؛ دخول أل التعريف دليل على اسمية الكلمة."],
    [74, "المثنى وجمع المذكر السالم علامة إعرابهما فرعية:", ["صح", "خطأ"], 0, "صح؛ كلاهما يعرب بالحروف لا بالحركات الأصلية."],
    [75, "كلمة (مئة) كُتبت الهمزة فيها على الياء لأنها:", ["مكسورة وما قبلها مكسور", "مجرورة وما قبلها مكسور", "مفتوحة وما قبلها مكسور", "مفتوحة وما قبلها مفتوح"], 2, "الهمزة مفتوحة وما قبلها مكسور (مِـئَـة)، والكسرة أقوى فترسم على نبرة."],
    [76, "في التلخيص يمكن وضع عنوان لكل فقرة:", ["صح", "خطأ"], 0, "وضع عناوين للفقرات خطوة تنظيمية مساعدة في مهارة التلخيص."],
    [77, "يخاطب المسؤول في الرسالة الرسمية في مقدمة الرسالة:", ["صح", "خطأ"], 0, "صح؛ يذكر لقبه واسمه وصفته الوظيفية في صدر ومقدمة الرسالة."],
    [78, "مراعاة علامات الترقيم في الكتابة تعين على:", ["تحقيق التناسب في المعنى", "تحديد المعنى بين البداية والنهاية", "تقسيم الكلام وترتيبه وتوضيح المقصود", "استيفاء عناصر المضمون"], 2, "علامات الترقيم تقسم الكلام وترتبه وتوضح المعاني ومواضع الوقف."],
    [79, "حالة النصب مشتركة بين الأسماء والأفعال:", ["صح", "خطأ"], 0, "صح؛ الرفع والنصب يشترك فيهما الاسم والفعل."],
    [80, "الناس مقسمون إلى شعوب و...... ليتعارفوا:", ["قبائلاً", "قبائلِ", "قبائلَ", "قبائلُ"], 2, "قبائلَ (معطوفة مجرورة بالفتحة لأنها ممنوعة من الصرف على صيغة منتهى الجموع)."],
    [81, "الكلمات المعربة تشمل:", ["أفعالاً وأسماء", "أسماء وحروفاً", "حروفاً وأفعالاً", "حروفاً فقط"], 0, "الإعراب يدخل الأسماء والفعل المضارع، ولا يدخل الحروف إطلاقاً."],
    [82, "علامة نصب جمع المؤنث السالم:", ["الياء", "الكسرة", "الفتحة", "السكون"], 1, "الكسرة نيابة عن الفتحة."],
    [83, "(زيد كاتب شاعر) الكلمتان كاتب وشاعر في الجملة السابقة:", ["الأولى خبر والثانية بدل", "الأولى خبر والثانية توكيد", "خبران للمبتدأ", "خبران للمضارع"], 2, "تعدد الخبر لمبتدأ واحد."],
    [84, "صاحب قصيدة المساء هو:", ["خليل مطران", "ميخائيل نعيمة", "أبو خليل القباني", "المتنبي"], 0, "الشاعر خليل مطران."],
    [85, "التاء المربوطة في (تمرة)، للتفريق بين الواحد وجنسه:", ["صح", "خطأ"], 0, "صح؛ مثل: تمر وتمرة، شجر وشجرة."],
    [86, "قرأتُ ...... من مقدمة الكتاب:", ["جزء", "جزءن", "جزءاً", "جزئين"], 2, "جزءاً (تنوين نصب تلحقه ألف لأن ما قبل الهمزة حرف ساكن لا يتصل)."],
    [87, "يجر الممنوع من الصرف بفتحة عوضاً عن الكسرة إذا كان:", ["مضافاً", "محلى بأل", "مجرداً من أل والإضافة", "معرفاً"], 2, "يشترط لجره بالفتحة أن يكون خالياً من (أل) وغير مضاف."],
    [88, "الفعل الماضي مبني دائماً:", ["صح", "خطأ"], 0, "الفعل الماضي يلزم البناء في كل حالاته."],
    [89, "في قوله تعالى (وَلَا تَلْمِزُوا أَنفُسَكُمْ) تنبيه إلى أن:", ["ذكر عيوب أخيك المسلم هو في الحقيقة لمز للنفس", "ألا يعيب بعضنا بعضاً", "كل ما ذكر صحيح", "الأمر خاص بالنفس فقط"], 2, "الآية جعلت المسلمين كالجسد الواحد فمن عاب أخاه فكأنما عاب نفسه."],
    [90, "عند صياغة تلخيص ما فإننا نتوخى الإيجاز مع:", ["الالتزام التام بألفاظ النص الأصلية", "عدم الوقوع في أسر الألفاظ الأصلية والتركيز على المعنى", "الابتعاد التام عن المعنى الأصلي", "زيادة الأمثلة والشروح"], 1, "التلخيص يعتمد على صياغة الفكرة بأسلوب الكاتب دون نسخ الألفاظ بحذافيرها."],
    [91, "في جملة (يجتهد الطالب لينجح) كلمة يجتهد فعل مضارع مبني على الضم:", ["صح", "خطأ"], 1, "خطأ؛ فعل مضارع مرفوع وعلامة رفعه الضمة (معرب وليس مبنياً)."],
    [92, "إني أقمت على التعلة بالمنى في غربة قالوا تكون دوائي؛ التعلة هي المرض:", ["صح", "خطأ"], 1, "خطأ؛ التعلة تعني التلهي والتشاغل بالأماني."],
    [93, "يقول مطران (عبث طوافي في البلاد...):", ["يعبر عن عدم فائدة سفره", "يعبر عن لا نهاية سفره", "يعبر عن استحالة سفره", "يعبر عن التخطيط للسفر"], 0, "طوافه وسفره كان عبثاً وبلا جدوى في شفاء جراحه وآلامه."],
    [94, "تمتاز الرسائل الرسمية بـ:", ["العاطفة", "الإسهاب", "الموضوعية", "جميع ما ذكر"], 2, "تمتاز الرسائل الإدارية والرسمية بالموضوعية والدقة."],
    [95, "(فيجيبني برياحه الهوجاء) معنى الهوجاء:", ["الشديدة العاتية", "المدمرة", "العالية", "الباردة"], 0, "الرياح الهوجاء هي الشديدة العاتية السريعة."],
    [96, "في جمع المؤنث السالم تكون الكسرة نائبة عن الفتحة في حالة:", ["الجر", "النصب", "الرفع", "الجزم"], 1, "في حالة النصب فقط (رأيت الطالباتِ)."],
    [97, "القوي والضعيف ...... أمام القانون:", ["يستوي", "يستوون", "يستويان", "تستوي"], 2, "يستويان (فعل مضارع مسند لألف الاثنين الدالة على المثنى)."],
    [98, "(حضر المباراة كثير من المشجعون) الجملة السابقة صحيحة إعرابياً:", ["صح", "خطأ"], 1, "خطأ؛ لأنها اسم مجرور بـ (من) وعلامة جره الياء (المشجعين)."],
    [99, "علامات الترقيم في الكتابة تعين القارئ على:", ["الكتابة الصحيحة", "معرفة البناء والإعراب", "تنويع الحركات الإعرابية", "تنويع النبرات الصوتية"], 3, "تساعد في تمييز نبرات الاستفهام والتعجب والوقفات."],
    [100, "تعين القارئ من العناء في فهم المعنى وتغير نبرات الصوت عند القراءة:", ["علامات الترقيم", "علامات التوقف", "علامات الإعراب", "علامات الجزم"], 0, "علامات الترقيم."],
    [101, "يشترط في الرسائل بنوعيها أن تكون التحية مذيلة بلفظ (وبعد):", ["صح", "خطأ"], 0, "التحية الرسمية تختم بكلمة وبعد كفاصل انتقال للمضمون."],
    [102, "وألبستني ثوب الضنى فلبسته، كلمة الضنى تعني:", ["الأولاد", "المرض", "العشق", "الهوى"], 1, "الضنى هو المرض والهُزال."],
    [103, "يعبر الشاعر في قصيدة في الغزل العفيف عن:", ["الغضب", "جمال اللقاء", "ألم الفراق والهوى", "اللوم"], 2, "معاناة وألم فراق المحبوبة."],
    [104, "تكتب الهمزة المتطرفة على الألف إذا كان ما قبلها مكسوراً:", ["صح", "خطأ"], 1, "خطأ؛ ترسم على الياء/النبرة إذا كان ما قبلها مكسوراً."],
    [105, "(فاك لا ينطق إلا بالحق) العبارة السابقة نحوياً:", ["صح", "خطأ"], 1, "خطأ؛ التصحيح: (فوك) مبتدأ مرفوع وعلامة رفعه الواو لأنه من الأسماء الخمسة."],
    [106, "علامة الاستفهام الإنكاري توضع في:", ["نهاية السؤال العادي", "نهاية الجملة الجامعة بين الاستفهام والتعجب أو الإنكار", "آخر جمل الحزن", "وسط الجملة"], 1, "توضع الجمع بين علامتي الاستفهام والتعجب (?!) للإنكار."],
    [107, "(لَا يَلِتْكُم مِّنْ أَعْمَالِكُمْ شَيْئًا) لا يلتكم أي:", ["لا ينقصكم", "لا يقبلكم", "لا يسامحكم", "لا يردكم"], 0, "لا ينقصكم من أجور أعمالكم شيئاً."],
    [108, "(ينتابها موج كموج مكارهي) معنى كلمة ينتابها:", ["يخالفها", "يعاودها مرة بعد مرة", "يوافقها", "يركبها"], 1, "ينتاب الشيء أي يتردد عليه ويعاوده دورياً."],
    [109, "علامة نصب المؤنث السالم:", ["الياء", "الكسرة", "الفتحة", "الضمة"], 1, "الكسرة نائبة عن الفتحة."],
    [110, "زيد كاتب شاعر. الكلمتان (كاتب) و(شاعر):", ["الأولى خبر والثانية بدل", "الأولى خبر والثانية توكيد", "خبران للمبتدأ", "فعلان"], 2, "خبران متتاليان لمبتدأ واحد."],
    [111, "تضمنت آيات سورة الحجرات نهياً عن مجموعة آفات وفي مقدمتها أكل الربا:", ["صح", "خطأ"], 1, "خطأ؛ السورة ركزت على آفات اللسان كالسخرية واللمز والتنابز والغيبة."],
    [112, "الواو في (بنو أخي) لا تزاد بعدها الألف الفارقة لأنها:", ["أصلية", "علامة إعراب", "زائدة", "ضمير"], 1, "لأنها واو جمع المذكر السالم (علامة إعراب) وليست واو الجماعة."],
    [113, "(ثاوٍ على صخر أصم...) جمع كلمة أصم:", ["أصماء", "صُمّ", "صمام", "أصامّ"], 1, "جمع أصم هو صُمّ."],
    [114, "(والبحر خفاق الجوانب ضائق...) معنى كلمة خفاق:", ["هادئ", "مضطرب", "متمرد", "واسع"], 1, "الخفقان هنا هو الاضطراب الشديد."],
    [115, "ترتيب الحركات من حيث القوة والضعف:", ["الفتحة فالضمة فالكسرة", "الكسرة فالضمة فالسكون", "الكسرة فالضمة فالفتحة فالسكون", "الضمة فالسكون"], 2, "أقواها الكسرة ثم الضمة ثم الفتحة وأضعفها السكون."],
    [116, "يرفع جمع المذكر السالم بـ:", ["الواو", "ثبوت النون", "الواو والنون معاً", "الألف"], 0, "يرفع بالواو وحدها (والنون عوض عن التنوين)."],
    [117, "ركزت سورة الحجرات على:", ["بناء الفرد والمجتمع سلوكياً وأخلاقياً", "المجتمع دون الأفراد", "التأكيد على الجماعة فقط", "الفرد فقط"], 0, "ترسيخ الآداب الفردية والاجتماعية."],
    [118, "الكتابة صفة يكتسبها طالبها:", ["بالموهبة فقط", "بالتعليم النظري", "بالوراثة", "بالتمرس والمران"], 3, "الممارسة والتمرس المستمر."],
    [119, "تكون الألف علامة رفع في:", ["جمع المذكر", "الأسماء الخمسة", "المثنى وما ألحق به", "الفعل الماضي"], 2, "الألف علامة رفع خاصة بالمثنى وملحقاته."],
    [120, "الإيجاز من خصائص الرسائل الإخوانية:", ["صح", "خطأ"], 1, "خطأ؛ الإيجاز من خصائص الرسائل الرسمية، أما الإخوانية فتحتمل الإسهاب."],
    [121, "(أَيُحِبُّ أَحَدُكُمْ أَن يَأْكُلَ لَحْمَ أَخِيهِ مَيْتًا) الآية تنفر من:", ["النميمة", "التنابز", "التجسس", "الغيبة"], 3, "الغيبة."],
    [122, "(والأفق معتكر قريح جفنه...) معنى معتكر:", ["قلق", "متألم", "مظلم وكدر", "ممتد"], 2, "معتكر أي كدر ومظلم مغبر."],
    [123, "مررت بالطالبات ...... تفوقن:", ["التي", "الذين", "اللاتي", "اللتين"], 2, "اللاتي أو اللائي لجمع الإناث."],
    [124, "(إِنَّمَا الْمُؤْمِنُونَ إِخْوَةٌ) المؤمنون تعرب:", ["مبتدأ مرفوع بالضمة", "مبتدأ مرفوع بالواو", "اسم إن مرفوع", "اسم إن منصوب"], 1, "(ما) كافة كفت إن عن العمل، فالمؤمنون مبتدأ مرفوع بالواو."],
    [125, "صاحب نص في الغزل العفيف هو حافظ إبراهيم:", ["صح", "خطأ"], 1, "خطأ؛ هو أحمد شوقي."],
    [126, "(إِنَّ الْحَسَنَاتِ يُذْهِبْنَ السَّيِّئَاتِ) كلمة الحسنات:", ["اسم مجرور بالكسرة", "اسم إن منصوب بالفتحة", "اسم إن منصوب بالفتحة المقدرة", "اسم إن منصوب وعلامة نصبه الكسرة"], 3, "اسم إن منصوب بالكسرة لأنه جمع مؤنث سالم."],
    [127, "(وَلَا تَلْمِزُوا أَنفُسَكُمْ) معنى تلمزوا:", ["تضربوا", "تغمزوا", "تلقبوا", "تعيبوا"], 3, "تعيبوا بعضكم بعضاً."],
    [128, "عند التثنية نقول: (قرأتُ الصحيفتان اليوميتان):", ["صح", "خطأ"], 1, "خطأ؛ التصحيح: (الصحيفتين) مفعول به منصوب بالياء."],
    [129, "تمتاز الرسائل الرسمية بـ:", ["الإسهاب", "الموضوعية", "العاطفة", "المبالغة"], 1, "الموضوعية."],
    [130, "تنصب الأسماء الخمسة بـ:", ["الياء", "الواو", "الألف", "الكسرة"], 2, "تنصب بالألف (رأيت حماك)."],
    [131, "يذكر اسم المرسل بوضوح مع تاريخ تحرير الرسالة في الرسائل الرسمية:", ["صح", "خطأ"], 0, "من العناصر والمتممات الأساسية في الرسالة الرسمية."],
    [132, "يجر الممنوع من الصرف المجرد من أل والإضافة بـ:", ["الفتحة", "الكسرة", "الياء", "الضمة"], 0, "الفتحة نيابة عن الكسرة."],
    [133, "النقطتان الرأسيتان (:) توضعان:", ["بين القول ومقوله", "بين الجمل الطويلة", "بين السبب والمسبب", "في نهاية الفقرة"], 0, "بعد القول وأشباهه (قال:)."],
    [134, "إذا كان خبر (إن) جملة أو شبه جملة فإنه يكون:", ["في محل رفع", "في محل نصب", "منصوباً", "في محل جزم"], 0, "خبر إن مرفوع دائماً أو في محل رفع."],
    [135, "الهمزة في كلمة (استغفار) همزة وصل:", ["صح", "خطأ"], 0, "مصدر فعل سداسي فهمزته وصل."],
    [136, "المبني هو الذي لا تتغير فيه حركة الحرف الأخير حسب الموقع الإعرابي:", ["صح", "خطأ"], 0, "هذا هو مفهوم البناء لزوماً لحركة واحدة."],
    [137, "في قول الشاعر: (يا للغروب وما به من عَبْرَةٍ للمستهام وعِبْرَةٍ للرائي):", ["تأثير على المحب فقط", "تأثير على المتأمل فقط", "تأكيد تأثير وقت الغروب على العاشق والمتأمل معاً", "محبته للغروب"], 2, "العَبْرة للمحب والعِبْرة للمتأمل."],
    [138, "(وَكَانَ اللَّهُ غَفُورًا رَّحِيمًا) إعراب رحيماً:", ["خبر أول", "اسم كان", "مبتدأ مؤخر", "خبر ثانٍ منصوب"], 3, "خبر ثانٍ لكان منصوب."],
    [139, "قوله تعالى: (وَلَا تَنَابَزُوا بِالْأَلْقَابِ):", ["لا تعايروا وتداعوا بالألقاب السيئة", "ذكروا بعضكم بالألقاب", "تناشدوا بالألقاب", "افتخروا بالأنساب"], 0, "النهي عن النداء بالألقاب المستكرهة."],
    [140, "(والأفق معتكر قريح جفنه...) جمع كلمة قريح:", ["قرحاوات", "قَرْحَى", "قرائح", "قريحات"], 1, "جمع قريح هو قَرْحَى."],
    [141, "واحد مما يلي يعد جمع مذكر سالماً:", ["السفريات", "المسافرون", "الأسفار", "السفرات"], 1, "المسافرون (مفرده مسافر)."],
    [142, "من علامات الإعراب الفرعية الضمة:", ["صح", "خطأ"], 1, "خطأ؛ الضمة هي أصل علامات الرفع الأصلية."],
    [143, "(أنا طيرُ الصباح) الخبر هنا جملة اسمية:", ["صح", "خطأ"], 1, "خطأ؛ الخبر كلمة (طيرُ) وهو مفرد."],
    [144, "تزاد الواو في (عمرو) خطاً ولا تلفظ للتفريق بينها وبين (عمر):", ["صح", "خطأ"], 0, "قاعدة إملائية مطردة للتفريق بين العلمين."],
    [145, "عند تنوين كلمة (ضوء) تنوين نصب تصبح ضوا:", ["صح", "خطأ"], 1, "خطأ؛ تكتب (ضوءاً) لأن ما قبلها حرف ساكن لا يوصل."],
    [146, "جميع ما يأتي من علامات الفعل ما عدا:", ["تاء التأنيث", "التنوين", "نون النسوة", "تاء الفاعل"], 1, "التنوين يختص بالأسماء فقط."],
    [147, "في قوله تعالى (فتصبحوا على ما فعلتم نادمين) دلالة على:", ["التحذير من الوقوع في الحسرة والندم عند الاستعجال في الحكم على الأخبار", "رفض الأخبار", "قبول كل الأخبار", "عدم الالتفات للأنباء"], 0, "دعوة للتثبت لعدم الندم."],
    [148, "الألف التي تزاد بعد واو الجماعة تسمى:", ["الألف اللينة", "الألف الفارقة", "المقصورة", "الممتدة"], 1, "الألف الفارقة للتفريق بين واو الجماعة والواو الأصلية."],
    [149, "(أعجبني ما في المتجر من معروضات) كلمة (ما) هي:", ["اسم موصول", "اسم شرط", "اسم استفهام", "حرف مبني"], 0, "اسم موصول بمعنى (الذي)."],
    [150, "علامة الترقيم في قولنا: (فُصِل الموظف من عمله ... فهو مهمل):", ["الفاصلة", "الفاصلة المنقوطة (؛)", "النقطة", "التعجب"], 1, "الفاصلة المنقوطة توضع بين جملتين إحداهما سبب للأخرى."],
    [151, "كلمة (أُذُن) همزتها:", ["وصل", "همزة قطع", "تعدية", "سطر"], 1, "همزة قطع لأنها اسم."],
    [152, "صورة المبتدأ في جملة (هذا أخي):", ["اسم إشارة", "اسم صريح", "ضمير منفصل", "ضمير مستتر"], 0, "اسم إشارة مبني في محل رفع مبتدأ."],
    [153, "(لَا يَلِتْكُم مِّنْ أَعْمَالِكُمْ شَيْئًا) لا يلتكم تعني:", ["لا ينقصكم", "لا يرد", "لا يتقبل", "لا يقبل"], 0, "لا ينقصكم."],
    [154, "توضع علامات الترقيم أثناء الكلام لتساعد القارئ على بيان مواضع الوقف:", ["صح", "خطأ"], 0, "صح؛ تبين أماكن الوقف والوصل وتمايز المعاني."],
    [155, "من علامات الاسم:", ["دخول حرف جر عليه", "دخول لم عليه", "اتصاله بنون النسوة", "دخول قد عليه"], 0, "الجر بالحروف من علامات الأسماء الخاصة بها."],
    [156, "من الكلمات التي فيها حرف يكتب ولا ينطق:", ["تلك", "هذان", "أولئك", "سماء"], 2, "الواو في (أولئك) تكتب ولا تنطق."],
    [157, "من الكلمات التي فيها حرف يكتب ولا ينطق:", ["عمرو", "حضرموت", "إبراهيم", "مكة"], 0, "الواو في عمرو تكتب ولا تلفظ."],
    [158, "من الكلمات التي فيها حرف يكتب ولا ينطق:", ["أولئك", "تلك", "هذان", "كل ما كتب"], 0, "أولئك فيها واو زائدة خطاً."],
    [159, "من الكلمات التي فيها حرف ينطق ولا يكتب:", ["حتى", "استغفر", "لكن", "لعل"], 2, "ننطق ألفاً بعد اللام في (لكن) ولا نكتبها."],
    [160, "من الكلمات التي فيها حرف ينطق ولا يكتب:", ["حتى", "استغفر", "طه", "سماء"], 2, "تلفظ طاهَا وتكتب طه."],
    [161, "إذا سبقت الأفعال الخمسة بأداة نصب فإن علامة نصبها:", ["الفتحة الظاهرة", "الفتحة المقدرة", "حذف النون", "حذف الخبر"], 2, "تنصب وتجزم بحذف النون."],
    [162, "الفعل المكتوب هجائياً بشكل صحيح هو:", ["قضا", "دنا", "مضا", "سهی"], 1, "دنا يكتب بالألف القائمة لأن أصله واوي (يدنو)."],
    [163, "هذا منظر ...... للنظر:", ["ملفت", "لافت", "لفات", "يلفت"], 1, "لافت من الفعل الثلاثي (لفت فهو لافت)."],
    [164, "من الأحرف المشبهة بالفعل:", ["كأنّ", "لكنّ", "لعلّ", "كل الخيارات صحيحة"], 3, "أخوات إن كلها أحرف مشبهة بالفعل."],
    [165, "الكلمة التي كتبت ألفها بشكل صحيح هي:", ["مشي", "دعى", "سمى", "عفا"], 3, "عفا (يعفو) تكتب بالألف القائمة لأن أصلها واو."],
    [166, "إذا تقدم الاسم على الفعل في الجملة فإنها تعد:", ["جملة فعلية", "جملة اسمية", "فعل ماض", "فعل أمر"], 1, "تصير جملة اسمية لتصدر المبتدأ فيها."],
    [167, "إذا سبق الفعل (نشتري) بأداة جزم فإن علامة جزمه:", ["السكون", "حذف النون", "حذف حرف العلة", "الكسرة"], 2, "حذف حرف العلة (لم نشترِ)."],
    [168, "تكتب الألف اللينة في نهاية الأفعال الثلاثية قائمة إذا كان أصلها:", ["ياء مد", "واواً", "ياءً", "ألفاً"], 1, "إذا كان أصلها واواً مثل: دعا وعفا وسما."],
    [169, "إذا سبقت الأفعال الخمسة بناصب فعلامة نصبها:", ["الفتحة", "حذف النون", "الفتحة الظاهرة", "ثبوت النون"], 1, "حذف النون."],
    [170, "الالتزام بضوابط المتنزهات (أنا ... مراعاتها):", ["أرجوا", "أرجو", "يرجوا", "نرجوا"], 1, "أرجو (الواو أصلية فلا تلحقها الألف الفارقة)."],
    [171, "الاسم المكتوب بشكل صحيح:", ["يحيى", "دنيا", "عصا", "كل ما كتب"], 3, "كلها صحيحة حسب ضوابط الألف المتطرفة."],
    [172, "الجملة المكتوبة بشكل صحيح من التالي:", ["محمد يدعوا", "محمد يرجو", "محمد يسعوا", "محمد يرجوا"], 1, "محمد يرجو (بدون ألف بعد الواو الأصلية)."],
    [173, "الأفعال الخمسة هي كل مضارع اتصل بألف الاثنين أو واو الجماعة أو ياء المخاطبة:", ["صح", "خطأ"], 0, "صح؛ هذا هو حدها النحوي."],
    [174, "جمع المؤنث السالم هو ما دل على أكثر من اثنتين بزيادة ألف وتاء على مفرده:", ["صح", "خطأ"], 0, "صح."],
    [175, "بعض الحروف مبنية:", ["صح", "خطأ"], 1, "خطأ؛ الحروف كلها مبنية بلا استثناء."],
    [176, "علامة جر الأسماء الخمسة:", ["الكسرة", "الألف", "الياء", "الواو"], 2, "تجر بالياء (مررت بأبيك)."],
    [177, "يحرص ...... الجامعة على تفوق طلابهم:", ["محاضرون", "محاضروا", "محاضرو", "محاضرين"], 2, "محاضرو (تحذف النون للإضافة ولا نضع ألفاً لأنها واو جمع مذكر سالم)."],
    [178, "أتى الفعل المضارع مبنياً في المثال التالي:", ["الطلاب يذاكرون", "يدعو المؤمن ربه", "لن يفلح الظالمون", "المؤمنات يحرصْنَ على دينهن"], 3, "(يحرصْنَ) مبني على السكون لاتصاله بنون النسوة."],
    [179, "هو الاسم الذي لا يقبل التنوين ولا الكسرة في الأصل:", ["الفاعل", "المذكر السالم", "الممنوع من الصرف", "العدد"], 2, "الممنوع من الصرف يمنع من التنوين ويجر بالفتحة."],
    [180, "صفة منتهية بألف ونون زائدتين:", ["غضبان", "عثمان", "شعبان", "رمضان"], 0, "غضبان (صفة على وزن فَعْلان)، أما البقية فأعلام."],
    [181, "(وبي رَشَأٌ قد كان دنياي...) كلمة رَشَأ تعني:", ["الأسد", "الحبل", "الصغير من الغزلان", "النسر"], 2, "الرَّشَأ هو ابن الظبية والغزال."],
    [182, "من مميزات الرسائل الرسمية البعد عن الخيال والعاطفة والإيجاز غير المخل:", ["صح", "خطأ"], 0, "صح؛ هي ركائز الرسائل الوظيفية."],
    [183, "الجزم من علامات الفعل:", ["المضارع", "الماضي", "الأمر", "المستقبل"], 0, "الجزم يختص بالفعل المضارع فقط."],
    [184, "من الأعلام المركبة تركيباً مزجياً:", ["عبد العزيز", "ست البنات", "نيويورك", "فاطمة الزهراء"], 2, "نيويورك وبعلبك ومعديكرب مركبة تركيباً مزجياً."],
    [185, "المفعول به مرفوع دائماً:", ["صح", "خطأ"], 1, "خطأ؛ المفعول به من المنصوبات دائماً."],
    [186, "المفعول به منصوب دائماً:", ["صح", "خطأ"], 0, "صح."],
    [187, "بعض الحروف مبنية:", ["صح", "خطأ"], 1, "خطأ؛ كل الحروف مبنية."],
    [188, "من حروف الجزم:", ["أنْ", "كي", "لن", "لا الناهية"], 3, "لا الناهية، ولم، ولما، ولام الأمر حروف جازمة."],
    [189, "حذفت تاء تتفاعلوا في قوله (ولا تنابزوا) للخفة ودفع الثقل:", ["صح", "خطأ"], 0, "صح؛ حذفت إحدى التاءين تخفيفاً."],
    [190, "من علامات الإعراب الفرعية: الفتحة في الممنوع من الصرف:", ["صح", "خطأ"], 0, "صح؛ لأنها نائبة عن الكسرة في حالة الجر."],
    [191, "تختص نون النسوة بالفعل المضارع فقط:", ["صح", "خطأ"], 1, "خطأ؛ تتصل بالماضي (كتبْنَ) والمضارع (يكتبْنَ) والأمر (اكتبْنَ)."],
    [192, "الفعل المضارع في (لن تذهبوا اليوم) منصوب وعلامة نصبه:", ["الفتحة المقدرة", "الفتحة الظاهرة", "حذف النون", "الضمة"], 2, "حذف النون لأنه من الأفعال الخمسة."],
    [193, "(حضر اليوم عشرون زائراً) تعد كلمة عشرون:", ["جمع تكسير", "عدداً مركباً", "ملحقاً بجمع المذكر السالم", "جمع مذكر سالماً"], 2, "ملحقة بجمع المذكر السالم لأن لا مفرد لها من لفظها."],
    [194, "من الأسماء المبنية مما يلي:", ["اللذان", "هاتين", "اللتان", "هذا"], 3, "هذا اسم إشارة مبني."],
    [195, "من الأسماء المبنية:", ["الظروف المركبة وأسماء الشرط", "أسماء الشرط", "الأعداد المركبة", "كل ما سبق"], 3, "كل هذه الأصناف من المبنيات."],
    [196, "من الأسماء المبنية:", ["الأسماء الخمسة", "أسماء الشرط والاستفهام", "جمع المذكر", "المثنى"], 1, "أسماء الشرط والاستفهام مبنية."],
    [197, "عند كتابة الهمزة المتطرفة ينظر إلى حركتها وحركة ما قبلها:", ["صح", "خطأ"], 1, "خطأ؛ ينظر لحركة الحرف السابق لها فقط."],
    [198, "عند كتابة الهمزة المتطرفة ينظر لما قبلها فقط دون النظر لحركتها:", ["صح", "خطأ"], 0, "صح."],
    [199, "الحروف كلها:", ["معربة", "مبنية", "مرفوعة", "مجزومة"], 1, "مبنية دائماً."],
    [200, "صيغة منتهى الجموع هي كل جمع مؤنث سالم:", ["صح", "خطأ"], 1, "خطأ؛ هي كل جمع تكسير بعد ألف تكسيره حرفان أو ثلاثة أوسطها ساكن."],
    [201, "(قَالَتِ الْأَعْرَابُ آمَنَّا قُل لَّمْ تُؤْمِنُوا...) تبين الآيات للأعراب حقيقة الإيمان والفرق بينه وبين الإسلام:", ["صح", "خطأ"], 0, "صح؛ الإسلام استسلام بالظاهر والإيمان تصديق ورسوخ بالقلب."],
    [202, "الأفعال المعتلة هي التي تحتوي أحرف العلة:", ["الواو", "الألف", "الياء", "جميع ما سبق"], 3, "أحرف العلة هي الألف والواو والياء."],
    [203, "اسم جاء على صورة الفعل الممنوع من الصرف:", ["زينب", "يزيد", "يوسف", "محمد"], 1, "يزيد وأحمد ويشكر على وزن الفعل."],
    [204, "عند تثنية كلمة (مبدأ) تصبح:", ["مبدؤان", "مبدأان", "مبدآن", "مبدءان"], 2, "تدمج الهمزة والألف في ألف مد (مبدآن)."],
    [205, "من خصائص الرسالة الإدارية: دقة اختيار المفردات والمصطلحات المناسبة:", ["صح", "خطأ"], 0, "صح."],
    [206, "صليت في مساجدَ كثيرة. تعرب مساجد اسم مجرور وعلامة جره:", ["الكسرة", "الكسرة المقدرة", "الفتحة الظاهرة نيابة عن الكسرة", "الفتحة المقدرة"], 2, "لأنه ممنوع من الصرف مجرد من أل والإضافة."],
    [207, "الهمزة المتطرفة ينظر إلى حركة الحرف السابق لها فقط:", ["صح", "خطأ"], 0, "صح."],
    [208, "الهمزة المتطرفة ينظر لحركتها وحركة ما قبلها:", ["صح", "خطأ"], 1, "خطأ؛ هذه الهمزة المتوسطة."],
    [209, "منعت كلمة (أحمد) من الصرف لأنها على صورة الفعل:", ["صح", "خطأ"], 0, "صح؛ للعلمية ووزن الفعل."],
    [210, "منعت كلمة أحمد من الصرف لأنها علم رباعي:", ["صح", "خطأ"], 1, "خطأ؛ لعلة وزن الفعل."],
    [211, "(وما الحب إلا طاعة) أسلوب قصر:", ["صح", "خطأ"], 0, "صح؛ نفي واستثناء."],
    [212, "التقيت بصديقين. يرفع المثنى بالألف وينصب ويجر بالياء:", ["صح", "خطأ"], 0, "صح."],
    [213, "يرفع المثنى بالواو وينصب بالألف ويجر بالياء:", ["صح", "خطأ"], 1, "خطأ."],
    [214, "من مسرحيات أحمد شوقي الشعرية:", ["الأيام", "التحدي", "الحنين", "مصرع كليوباترا"], 3, "مصرع كليوباترا ومجنون ليلى وعنترة."],
    [215, "عَلَمٌ على وزن فُعَل ممنوع من الصرف:", ["آخر", "فخر", "أول", "عُمَر"], 3, "عُمَر وزُفَر وزُحَل."],
    [216, "يختص حرف الجر (مِن) بالدخول على:", ["الجملة", "الفعل", "الاسم", "النداء"], 2, "يختص بالأسماء."],
    [217, "من علامات الاسم أن يقبل دخول:", ["حروف الجزم", "حروف الجر", "تاء الفاعل", "ياء المخاطبة مع الماضي"], 1, "الجر من خصائص الأسماء."],
    [218, "(قرأت جزءاً من القرآن) كلمة جزءاً مكتوبة هجائياً بشكل صحيح:", ["صح", "خطأ"], 0, "صح."],
    [219, "أنواع الإعراب عشرة:", ["صح", "خطأ"], 1, "خطأ؛ أنواع الإعراب أربعة: الرفع، النصب، الجر، الجزم."],
    [220, "أنواع الإعراب أربعة:", ["صح", "خطأ"], 0, "صح."],
    [221, "كل فعل مضارع اتصل بألف الاثنين أو واو الجماعة أو ياء المخاطبة:", ["المعتل", "الزائد", "الأفعال الخمسة", "الناقص"], 2, "الأفعال الخمسة."],
    [222, "جمع المذكر السالم يرفع بالألف:", ["صح", "خطأ"], 1, "خطأ؛ يرفع بالواو."],
    [223, "جمع المذكر السالم يرفع بالواو:", ["صح", "خطأ"], 0, "صح."],
    [224, "من مميزات البريد الإلكتروني إرسال الرسالة إلى العديد من الأشخاص في لحظة واحدة:", ["صح", "خطأ"], 0, "صح."],
    [225, "معنى الضنى: المرض والهُزال:", ["صح", "خطأ"], 0, "صح."],
    [226, "معنى الضنى: الحبيب:", ["صح", "خطأ"], 1, "خطأ؛ الضنى يعني المرض."],
    [227, "(كتب الأديب المقالاتِ) علامة إعراب المقالات:", ["الضمة", "الكسرة", "الفتحة", "السكون"], 1, "مفعول به منصوب بالكسرة لأنه جمع مؤنث سالم."],
    [228, "عند إسناد ياء المخاطبة لفعل الأمر (اعمل) يصبح:", ["اعملين", "اعمل", "اعملي", "إعملين"], 2, "اعملي (مبني على حذف النون)."],
    [229, "(وَلَا تَلْمِزُوا أَنفُسَكُمْ) تعني:", ["لا تداعوا بالألقاب", "لا تتجسسوا", "لا يعب بعضكم بعضاً", "لا تظلموا"], 2, "لا يعب بعضكم بعضاً."],
    [230, "(إبراهيم) اسم ممنوع من الصرف لاجتماع علتي العلمية و:", ["التأنيث", "العجمة", "التركيب", "الوزن"], 1, "العلم الأعجمي."],
    [231, "فاز ...... العلم بالجائزة:", ["طالبي", "طالبين", "طالبا", "طالبان"], 2, "طالبا (فاعل مرفوع بالألف وحذفت النون للإضافة)."],
    [232, "ما كان دالاً على معنى مقترن بزمن:", ["الاسم", "الحرف", "الفعل", "الصفة"], 2, "الفعل."],
    [233, "من علامات الإعراب الأصلية الواو:", ["صح", "خطأ"], 1, "خطأ؛ الواو علامة فرعية."],
    [234, "من علامات الإعراب الفرعية الواو:", ["صح", "خطأ"], 0, "صح."],
    [235, "تحذف نون المثنى عند إضافته إلى اسم أو ضمير:", ["صح", "خطأ"], 0, "صح (طالبا العلم)."],
    [236, "العاشق يستمتع بعشقه على الرغم مما يلقى فيه من هوان في نص شوقي:", ["صح", "خطأ"], 0, "صح."],
    [237, "الفعل الذي يقبل ياء المخاطبة من علاماته هو فعل الأمر والمضارع:", ["صح", "خطأ"], 0, "صح."],
    [238, "مفرد كلمة (أبناء) همزته همزة وصل:", ["صح", "خطأ"], 0, "صح؛ مفردها (ابن) وهو من الأسماء العشرة السماعية المبدوءة بوصل."],
    [239, "في (سُئِل) الشاهد، طبقنا قاعدة تغليب الحركة الأقوى:", ["صح", "خطأ"], 0, "صح؛ كُسرت بعد ضم والكسرة أقوى فكتبت على نبرة."],
    [240, "لا تحذف نون جمع المذكر السالم عند الإضافة:", ["صح", "خطأ"], 1, "خطأ؛ تحذف وجوباً."],
    [241, "نظف ...... من بقايا الطعام:", ["فيك", "فاك", "فوك", "فموك"], 1, "فاك (مفعول به منصوب بالألف لأنه من الأسماء الخمسة)."],
    [242, "المثنى هو ما دل على اثنين أو اثنتين بزيادة ألف ونون أو:", ["واو ونون", "ياء ونون في آخره", "ألف وتاء", "ياء فقط"], 1, "ألف ونون رفعاً أو ياء ونون نصباً وجراً."],
    [243, "لا تحذف نون جمع المذكر عند الإضافة:", ["صح", "خطأ"], 1, "خطأ."],
    [244, "(سلمت على الذي كرمني) يختص الجر بالأسماء فقط:", ["صح", "خطأ"], 0, "صح."],
    [245, "ذكر شوقي أنه طعن طعنتين هما:", ["طعنتا الغدر والخيانة", "الألم والحزن", "الحب والهوى", "طعنتا القَدّ والبَيْن"], 3, "طعنة القد (القوام) وطعنة البين (الفراق)."],
    [246, "أنواع الكلمة في العربية:", ["حرف", "فعل", "اسم", "جميع ما سبق"], 3, "اسم وفعل وحرف."],
    [247, "عسى من له الإحسان أن يغفر زلتي، الفعل المضارع معرب دائماً:", ["صح", "خطأ"], 1, "خطأ."],
    [248, "الإعراب يكون في الأفعال والأسماء والحروف:", ["صح", "خطأ"], 1, "خطأ؛ الحروف لا محل لها من الإعراب."],
    [249, "الحروف كلها مبنية ولا محل لها من الإعراب:", ["صح", "خطأ"], 0, "صح."],
    [250, "يبنى الفعل المضارع في حالتين: اتصاله بنون النسوة ونون التوكيد:", ["صح", "خطأ"], 0, "صح."],
    [251, "تتميز الرسائل الإخوانية بإمكانية إرسالها لعدد كبير بنفس الصيغة كتعميم:", ["صح", "خطأ"], 1, "خطأ؛ الرسائل الرسمية والإدارية هي التي تعمم."],
    [252, "كلمة (اللذين) اسم موصول معرب:", ["صح", "خطأ"], 0, "صح؛ ملحق بالمثنى."],
    [253, "عند الكتابة يراعى ترك فراغ في الهامش الأيمن بمقدار:", ["3 - 4 سم", "2 - 3 سم", "1 سم", "5 سم"], 1, "2 إلى 3 سم لتنسيق الورقة."],
    [254, "قرأ الطالب عن الشاعر الـ ......:", ["حطيأة", "حُطَيْئَة", "حطيؤة", "حطة"], 1, "الحُطَيْئَة (ترسم الهمزة على نبرة لأن ما قبلها ياء ساكنة بمثابة الكسرة)."],
    [255, "(أَيُحِبُّ أَحَدُكُمْ أَن يَأْكُلَ لَحْمَ أَخِيهِ مَيْتًا) أكل لحم الإنسان جاء هنا مجازياً:", ["صح", "خطأ"], 0, "صح؛ تمثيل مجازي بليغ لشناعة الغيبة."],
    [256, "البخيل لا مروءة له؛ طبقت على همزة (مروءة) قاعدة تغليب الحركة الأقوى:", ["صح", "خطأ"], 1, "خطأ؛ هذه حالة مستثناة (همزة مفتوحة بعد واو مد فترسم مفردة)."],
    [257, "ذهبت إلى ...... في منزله:", ["أخا", "أخاك", "أخيك", "أخوك"], 2, "أخيك (اسم مجرور بالياء لأنه من الأسماء الخمسة)."],
    [258, "كلمة (بيئة) مكتوبة إملائياً بشكل صحيح:", ["صح", "خطأ"], 0, "صح؛ همزة مفتوحة بعد ياء ساكنة ترسم على نبرة."],
    [259, "(سأستغفرُ الله) نوع الفعل مضارع:", ["صح", "خطأ"], 0, "صح؛ اقترن بالسين ودل على الحال والاستقبال."],
    [260, "أقوى الحركات الكسرة فالضمة ثم الفتحة فالسكون:", ["صح", "خطأ"], 0, "صح."],
    [261, "العفوية واستخدام الصور الخيالية من سمات الرسالة:", ["الإلكترونية الرسمية", "الرسمية", "الإخوانية الودية", "الديوانية"], 2, "الرسالة الإخوانية."],
    [262, "الهمزة في الفعل المضارع (أستغفِرُ) همزة:", ["قطع", "وصل", "متطرفة", "فصل"], 0, "همزة المضارعة تكون همزة قطع دائماً."],
    [263, "كلمة عشرون:", ["جمع تكسير", "ملحق بجمع المذكر السالم", "جمع مذكر سالم", "مؤنث"], 1, "ملحق بجمع المذكر السالم."],
    [264, "ترفع الأفعال الخمسة وعلامة رفعها ثبوت النون:", ["صح", "خطأ"], 0, "صح."],
    [265, "ترفع الأفعال الخمسة بالضمة المقدرة:", ["صح", "خطأ"], 1, "خطأ."],
    [266, "زار سعيد صديقه ......:", ["مساءً", "مساً", "مساء", "مساءاً"], 0, "مساءً (لا تزاد ألف التنوين بعد الهمزة المسبوقة بألف)."],
    [267, "فاز الطالبان؛ (الطالبان) مرفوعة بـ:", ["الواو", "الألف", "الضمة", "النون"], 1, "بالألف لأنه مثنى."],
    [268, "الحكمة من خلق الناس شعوباً وقبائل هي:", ["ليتميزوا بالأنساب", "ليتعارفوا ويتعاونوا", "ليشتهروا", "للتفاخر"], 1, "التعارف والتآلف (لتعارفوا)."],
    [269, "عمدة وأساس الجملة الفعلية:", ["مبتدأ وخبر", "فعل وخبر", "فعل وفاعل", "ظرف وجار"], 2, "الفعل والفاعل هما ركنا الجملة الفعلية."],
    [270, "معرب ويبنى في حالتين فقط من الأفعال:", ["الماضي", "الأمر", "المضارع", "اسم الفعل"], 2, "المضارع."],
    [271, "يبنى الفعل المضارع على السكون إذا اتصلت به:", ["ياء المخاطبة", "ألف الاثنين", "نون النسوة", "واو الجماعة"], 2, "نون النسوة."],
    [272, "علامة رفع الأفعال الخمسة:", ["الألف", "الواو", "الضمة", "ثبوت النون"], 3, "ثبوت النون."],
    [273, "الكلمة المعربة هي التي يتغير آخرها بتغير موقعها في الجملة:", ["صح", "خطأ"], 0, "صح."],
    [274, "جملة (جاء هذان الطالبان) كلمة (هذان):", ["اسم موصول", "اسم معرب", "اسم مبني", "مفرد"], 1, "معرب إعراب المثنى."],
    [275, "تحذف ألف (ابن) إذا وقعت بين علمين الثاني أب للأول ولم تقع في أول السطر:", ["صح", "خطأ"], 0, "صح (محمد بن خالد)."],
    [276, "رسمت الهمزة في (سُئِل) على نبرة لأنها:", ["مكسورة بعد سكون", "مكسورة بعد فتح", "مكسورة بعد ضم", "مفتوحة"], 2, "مكسورة وما قبلها مضموم."],
    [277, "الرسائل الرسمية تسمى بالرسائل:", ["الودية", "الإخوانية", "الرقمية", "الإدارية والديوانية"], 3, "الإدارية والديوانية."],
    [278, "قائل قصيدة الغزل العفيف المقررة هو:", ["المتنبي", "خليل مطران", "أحمد شوقي", "الشافعي"], 2, "أحمد شوقي."],
    [279, "تشتمل على شكر للمرسل إليه وعبارة دعاء في الرسالة الرسمية:", ["المقدمة", "العنوان", "عرض الموضوع", "الخاتمة"], 3, "الخاتمة."],
    [280, "(وَإِن طَائِفَتَانِ مِنَ الْمُؤْمِنِينَ اقْتَتَلُوا فَأَصْلِحُوا بَيْنَهُمَا) دعوة إلى:", ["التوثق", "التعارف", "الإصلاح والتوفيق وحقن الدماء", "القتال"], 2, "الإصلاح بين المؤمنين."],
    [281, "الكلمة المبنية هي التي يتغير آخرها بتغير موقعها:", ["صح", "خطأ"], 1, "خطأ؛ هذا تعريف المعرب، أما المبني فيلزم حالة واحدة."],
    [282, "المثنى هو ما زاد على:", ["واحد", "اثنين", "ثلاثة", "أربعة"], 2, ""],
    [283, "فعل مضارع منصوب وعلامة نصبه فتحة مقدرة:", ["لن يدريَ", "لن يسعى", "لن يذهبَ", "لن يسموَ"], 1, "لن يسعى (معتل بالألف فتقدر الفتحة)."],
    [284, "من سمات الرسالة ...... تزيين الأسلوب بالصور الخيالية والمشاعر:", ["الودية الإخوانية", "الرسمية", "الإدارية", "القضائية"], 0, "الإخوانية."],
    [285, "من علامات فعل الأمر قبوله ياء المخاطبة ودلالته على الطلب:", ["صح", "خطأ"], 0, "صح."],
    [286, "سمي جمع المذكر السالم سالماً لأن صورة مفرده تسلم من التغيير:", ["صح", "خطأ"], 0, "صح."],
    [287, "سمي جمع المذكر سالماً لأن صورة الجمع تسلم فيه من التغيير:", ["صح", "خطأ"], 1, "خطأ؛ صورة المفرد هي التي تسلم."],
    [288, "برع الشاعر أحمد شوقي في شعر الغزل الرقيق:", ["صح", "خطأ"], 0, "صح."],
    [289, "الكلمة التي تدل على شيء يدرك بالحواس أو العقل مجردة من الزمان:", ["الفعل", "الاسم", "الحرف", "الصفة"], 1, "الاسم."],
    [290, "عند كتابة الهمزة المتوسطة:", ["ننظر لحركتها فقط", "ننظر لحركة ما بعدها", "ننظر لحركتها وحركة الحرف السابق لها ونكتبها على ما يناسب الأقوى", "نكتبها عشوائياً"], 2, "قاعدة أقوى الحركات."],
    [291, "أقسام الكلام (اسم، وفعل، وحرف):", ["صح", "خطأ"], 0, "صح."],
    [292, "الهمزة في (استمر، انتشر) همزة:", ["وصل", "ضم", "قطع", "متطرفة"], 0, "وصل لأنها في ماضي وأمر ومصدر الخماسي والسداسي."],
    [293, "الأفعال الخمسة تعرب بعلامات إعراب:", ["فرعية (الحروف)", "أصلية", "جزم فقط", "سكون"], 0, "فرعية (ثبوت وحذف النون)."],
    [294, "بدأت المراسلات والبريد الإلكتروني في الظهور عام:", ["1970", "1971", "1972", "1980"], 1, "عام 1971م."],
    [295, "الحرف هو كلمة لها معنى في ذاتها:", ["صح", "خطأ"], 1, "خطأ؛ لا يظهر معناها إلا مع غيرها."],
    [296, "الحرف لا معنى له في ذاته وإنما يكتسب معناه بدخوله في الجملة:", ["صح", "خطأ"], 0, "صح."],
    [297, "يعرب جمع المؤنث السالم في حالة النصب بـ:", ["الفتحة", "الضمة", "الكسرة نيابة عن الفتحة", "السكون"], 2, "الكسرة."],
    [298, "يعرب الاسم الممنوع من الصرف في حالة الجر بـ:", ["الفتحة عوضاً عن الكسرة", "الكسرة", "الياء", "السكون"], 0, "الفتحة."],
    [299, "من متممات الرسالة الرسمية الشكلية:", ["المقدمة", "الشكر", "عنوان وتوقيع وتاريخ المرسل", "التشبيهات"], 2, "العنوان والتاريخ والتوقيع والصفة الوظيفية."],
    [300, "من شروط الكتابة الصحيحة:", ["السلامة اللغوية", "مراعاة علامات الترقيم", "التنسيق الشكلي", "جميع ما ذكر"], 3, "جميع ما ذكر متطلب للكتابة السليمة."],
    [301, "العدد (ثلاثون) ملحق بجمع المذكر السالم:", ["صح", "خطأ"], 0, "صح."],
    [302, "معنى كلمة (رشأ) الصغير من الغزلان:", ["صح", "خطأ"], 0, "صح."],
    [303, "كلمة (مصابيح) منعت من الصرف لأنها علم أعجمي:", ["صح", "خطأ"], 1, "خطأ؛ لأنها صيغة منتهى الجموع (مفاعيل)."],
    [304, "كلمة مصابيح منعت من الصرف لأنها صيغة منتهى الجموع:", ["صح", "خطأ"], 0, "صح."],
    [305, "علامة نصب الأفعال الخمسة ثبوت النون:", ["صح", "خطأ"], 1, "خطأ؛ حذف النون."],
    [306, "علامة نصب الأفعال الخمسة حذف النون:", ["صح", "خطأ"], 0, "صح."],
    [307, "إعراب الفعل في (الفتيات يَلْعَبْنَ):", ["مبني على السكون لاتصاله بنون النسوة", "معرب", "مرفوع بثبوت النون", "منصوب"], 0, "مبني على السكون."],
    [308, "(أدّ الأماناتِ إلى أهلها) الأمانات منصوبة بـ:", ["الضمة", "الكسرة", "الفتحة", "السكون"], 1, "مفعول به منصوب بالكسرة لأنه جمع مؤنث سالم."],
    [309, "هذا ...... للقرآن:", ["قارى", "قارئٌ", "قاري", "قارء"], 1, "قارئ (همزة متطرفة بعد كسر فترسم على ياء)."],
    [310, "(يا عبادَ الله اتقوا ربكم) العلامة الاسمية في (عباد) هي:", ["الجر", "التنوين", "النصب", "دخول النداء عليها"], 3, "قبول النداء من علامات الأسماء."],
    [311, "نوع اللام في قوله تعالى: (وَإِنَّ السَّاعَةَ لَآتِيَةٌ):", ["الناصبة", "الابتداء", "المزحلقة", "حرف جر"], 2, "اللام المزحلقة الواقعة في خبر إن."],
    [312, "تنظيم الهوامش وترك المسافات يخدم:", ["علامات الترقيم", "مراعاة الناحية الشكلية", "السلامة اللغوية", "المعنى"], 1, "الناحية الشكلية والتنسيقية."],
    [313, "(الطالبات يدرسْنَ باهتمام) يدرسن فعل مضارع مبني على الفتح:", ["صح", "خطأ"], 1, "خطأ؛ التصحيح: مبني على السكون لاتصاله بنون النسوة."],
    [314, "الكلمة التي تتغير حركة آخرها بتغير موقعها الإعرابي تسمى:", ["مبنية", "غير معربة", "معربة", "حرفاً"], 2, "الكلمة المعربة."],
    [315, "(إن المجتهدين مقدرون) نوع الخبر في الجملة:", ["جملة اسمية", "جملة فعلية", "مفرد", "شبه جملة"], 2, "مفرد (لأنه ليس جملة ولا شبه جملة)."],
    [316, "من الأسماء المعربة في لغتنا:", ["أسماء الشرط", "أسماء الاستفهام", "الأسماء الخمسة", "الضمائر"], 2, "الأسماء الخمسة معربة."],
    [317, "المثنى علامة رفعه الألف:", ["صح", "خطأ"], 0, "صح."],
    [318, "المعنى الذي يفيده الحرف (ليت) في الشعر:", ["التمني", "الاستدراك", "العطف", "الترجي"], 0, "ليت تفيد التمني للأمر المستحيل أو عسير التحقق."],
    [319, "(إِنَّ هَذَا لَفِي الصُّحُفِ الْأُولَى) اسم الإشارة هذا يعرب:", ["في محل نصب مفعول به", "في محل رفع مبتدأ", "في محل نصب اسم إنّ", "خبر إن"], 2, "اسم إنّ في محل نصب."],
    [320, "الفتحة علامة أصلية لحالة:", ["الجزم", "الرفع", "النصب", "الجر"], 2, "حالة النصب."],
    [321, "كلمة (الطالبان) اسم مثنى علامة رفعه ثبوت النون:", ["صح", "خطأ"], 1, "خطأ؛ علامة رفعه الألف (ثبوت النون للأفعال)."],
    [322, "في المثنى تكون الياء نائبة عن الفتحة في حالة:", ["الجزم", "الرفع", "النصب", "الجر"], 2, "حالة النصب."],
    [323, "أقبلَ ...... القرآن على كتب التفسير:", ["محبون", "محبي", "محبو", "محبين"], 2, "محبو (فاعل مرفوع بالواو وحذفت النون للإضافة دون وضع ألف)."],
    [324, "التاء المفتوحة تلفظ تاءً في الوقف والوصل:", ["صح", "خطأ"], 0, "صح."],
    [325, "الجملة التي استُخدمت فيها علامة الترقيم بشكل صحيح تماماً:", ["الجملة قسمان، اسمية", "تلبدت السماء بالغيوم؛ فنزل المطر", "هل أدلكم على تجارة!", "ذهب، محمد"], 1, "فاصلة منقوطة بين سبب ومسبب."],
    [326, "الواو في (فاعلوا الخير) لا تزاد بعدها ألف فارقة لأنها:", ["غير زائدة", "أصلية", "علامة إعراب جمع المذكر السالم", "زائدة"], 2, "لأنها واو جمع المذكر السالم وليست واو الجماعة المتصلة بالأفعال."],
    [327, "من متممات الرسالة الرسمية التوقيع وتاريخ الرسالة والجهة:", ["صح", "خطأ"], 0, "صح."],
    [328, "(حضر المباراة كثيرٌ من المشجعون) صحيحة نحوياً:", ["صح", "خطأ"], 1, "خطأ؛ والتصحيح: (من المشجعين)."],
    [329, "توضع علامتَا (?!) في نهاية الجمل المتعجب منها فقط دون استفهام:", ["صح", "خطأ"], 1, "خطأ؛ توضع في الاستفهام التعجبي الإنكاري."],
    [330, "علامة الحذف في الكلام يدل عليها بوضع نقطة واحدة:", ["صح", "خطأ"], 1, "خطأ؛ علامة الحذف ثلاث نقاط أفقية متتابعة (...)."],
    [331, "من علامات الإعراب الفرعية:", ["الفتحة والضمة", "الفتحة والسكون", "الألف والواو والياء", "الكسرة"], 2, "حروف العلة الثلاثة إذا نابت عن الحركات."],
    [332, "(يقضي المريض ما فاته في أيامٍ ...):", ["أخراً", "أُخَرَ", "أُخُرٍ", "أُخْرَى"], 1, "أُخَرَ (صفة مجرورة بالفتحة لأنها ممنوعة من الصرف على وزن فُعَل)."],
    [333, "من أهم ما يدخل في جانب الشكل استيفاء عناصر الموضوع المطلوب:", ["صح", "خطأ"], 1, "خطأ؛ استيفاء العناصر يخدم المضمون والمعنى أولاً."],
    [334, "تكتب كلمة (لؤلؤ) عند تنوينها بالفتح منصوبة على صورة:", ["لؤلؤة", "لؤلؤاً", "لؤلؤ", "لؤلواً"], 1, "لؤلؤاً (ترسم الهمزة على واو وتلحقها ألف التنوين)."],
    [335, "يجر الممنوع من الصرف بالكسرة الأصلية إذا كان:", ["محلى بأل أو مضافاً", "موصوفاً", "مجرداً", "علماً أعجمياً"], 0, "إذا دخلته (أل) أو أضيف."],
    [336, "الكلمات (أبوك، أخوك، حموك) تعد من الأفعال الخمسة:", ["صح", "خطأ"], 1, "خطأ؛ هي من الأسماء الخمسة."],
    [337, "(إِنَّ اللَّهَ عَزِيزٌ حَكِيمٌ) كلمة (حكيم) تعرب:", ["مبتدأ مؤخر", "خبر إنّ ثانٍ مرفوع", "اسم إن", "فاعل"], 1, "خبر إن ثانٍ مرفوع."],
    [338, "زيدت الواو خطاً وسقطت نطقاً في كلمة (أولئك):", ["صح", "خطأ"], 0, "صح."],
    [339, "(لكنّ) فعل من الأفعال الناسخة:", ["صح", "خطأ"], 1, "خطأ؛ حرف ناسخ مشبه بالفعل."],
    [340, "الكتابة صفة يكتسبها طالبها بـ:", ["التعلم النظري", "الوراثة", "الموهبة فقط", "التمرس والدربة والمران"], 3, "التمرس والمران المستمر."],
    [341, "نوع (ما) في جملة: (إنما العلمُ بالتعلم):", ["النافية", "الجارة", "التعجبية", "الكافة"], 3, "ما الكافة تكف (إن) عن العمل."],
    [342, "إذا أردنا إدخال (إنّ) على (أخوك ذو مال) نقول:", ["إن أخوك ذا مال", "إنّ أخاك ذو مالٍ", "إن أخيك ذا مال", "إن أخوك ذو مال"], 1, "تنصب اسمها بالألف وترفع خبرها بالواو."],
    [343, "واحدة من الكلمات الآتية نكرة:", ["هذا", "جامعة", "جامعة الكويت", "الجامعة"], 1, "جامعة (مجردة من أل والإضافة)، أما البقية فمعارف."],
    [344, "لا يفضل ربط عرض الموضوع في الرسالة الرسمية بالفاء مثل (فأفيدكم):", ["صح", "خطأ"], 0, "صح؛ يفضل الدخول في الموضوع مباشرة."],
    [345, "اتبعنا النصيحة التي ...... إلينا:", ["أسديته", "أسديتهم", "أسديتَها", "أسديتما"], 2, "أسديتها (الهاء تطابق النصيحة المؤنثة)."],
    [346, "الكسرة علامة نصب فرعية في:", ["جمع المذكر السالم", "جمع المؤنث السالم", "الأعلام", "الممنوع من الصرف"], 1, "جمع المؤنث السالم."],
    [347, "(المدرسان حاضران) نوع الخبر مفرد:", ["صح", "خطأ"], 0, "صح؛ مفرد في باب الخبر يعني ليس جملة ولا شبه جملة."],
    [348, "فرح ...... نالا الجائزة:", ["الذين", "اللذين", "اللذان", "اللتان"], 2, "اللذان (فاعل مرفوع بالألف)."],
    [349, "علامة التعجب (!) توضع في:", ["نهاية السؤال", "نهاية الموضوع التام", "نهاية الجمل المعبرة عن مشاعر وانفعال", "بين الجملتين"], 2, "الجمل الانفعالية والتعجبية."],
    [350, "(وَكَانَ أَبُوهُمَا صَالِحًا) إعراب (أبوهما):", ["اسم كان مرفوع بالألف", "اسم كان مرفوع وعلامة رفعه الواو لأنه من الأسماء الخمسة", "فاعل", "خبر"], 1, "اسم كان مرفوع بالواو."],
    [351, "الحرف والحركة المتجانسة: الحرف المناسب للكسرة هو:", ["الألف", "الواو", "الياء", "الهمزة"], 2, "الياء تجانس الكسرة."],
    [352, "(القتالُ عند الجبل) شبه الجملة الظرفية في محل:", ["رفع فاعل", "رفع خبر المبتدأ", "رفع مبتدأ", "نصب مفعول"], 1, "في محل رفع خبر."],
    [353, "توضع الفاصلة بين العدد والمعدود إذا كانا في أول السطر:", ["صح", "خطأ"], 0, "صح (مثل: أولاً، ثانياً،)."],
    [354, "(الجامعة المفتوحة صرحٌ ثقافي) كلمة (صرح) تعرب:", ["فاعل", "خبر المبتدأ مرفوع", "ماض", "مبتدأ"], 1, "خبر للمبتدأ (الجامعة)."],
    [355, "علامة نصب جمع المؤنث السالم الكسرة نيابة عن الفتحة:", ["صح", "خطأ"], 0, "صح."],
    [356, "توضع النقطة في نهاية الجملة غير التامة المعنى:", ["صح", "خطأ"], 1, "خطأ؛ توضع في نهاية الجملة تامة المعنى."],
    [357, "(العلم يدعو إلى الإيمان) جملة يدعو في محل:", ["رفع مبتدأ", "رفع خبر المبتدأ", "نصب خبر", "جر مضاف"], 1, "جملة فعلية في محل رفع خبر."],
    [358, "تختلف الرسالة الإخوانية عن الرسمية في:", ["اسم المرسل", "سلامة اللغة", "تقسيم الرسالة", "اشتمالها على الجمل الدعائية والعاطفة والإسهاب"], 3, "العاطفة وتنميق الألفاظ."],
    [359, "واحدة من الكلمات الآتية تعد جمع مذكر سالماً حقيقياً:", ["عشرون", "سنون", "أهلون", "مهندسون"], 3, "مهندسون؛ لأن لها مفرداً من لفظها سلم فيه بناء مفرده."],
    [360, "همزة كلمة (انطلاق) همزة وصل لأنها مصدر لفعل:", ["ثلاثي", "رباعي", "خماسي", "سداسي"], 2, "فعل خماسي (انطلق)."],
    [361, "في قوله تعالى (إِنَّ هَذَا لَفِي الصُّحُفِ الْأُولَى) يعرب هذا:", ["مبتدأ", "خبر", "مفعول به", "في محل نصب اسم إن"], 3, "اسم إن في محل نصب."],
    [362, "الحرف المتجانس المناسب للضمة عند كتابة الهمزة:", ["الألف", "الياء", "الواو", "التاء"], 2, "الواو."],
    [363, "(تضحياتُ الذين استشهدوا لا تذهب سدى) إعراب تضحيات:", ["مبتدأ منصوب", "مبتدأ مرفوع بالضمة", "خبر", "فاعل"], 1, "مبتدأ مرفوع بالضمة."],
    [364, "في جمع المذكر السالم تكون الياء نائبة عن الكسرة في حالة:", ["الجزم", "الجر", "النصب", "الرفع"], 1, "في حالة الجر (مثل: سلمت على المعلمين)."],
    [365, "استيفاء عناصر الموضوع في الكتابة يخدم المضمون قبل الشكل:", ["صح", "خطأ"], 0, "صح."],
    [366, "تأتي همزة الوصل دائماً في:", ["أول الكلمة", "وسط الكلمة", "آخر الكلمة", "في كل المواضع"], 0, "همزتا الوصل والقطع في ابتداء وأول الكلمات."],
    [367, "الألف في الفعل (هدى) منقلبة عن أصل وهو الياء:", ["صح", "خطأ"], 0, "صح؛ بدليل المضارع (يهدي) ولذلك رسمت ياء."],
    [368, "أقسم الجندي: ... الأوامر:", ["ليطيعَنَّ", "ليطع", "ليطيع", "ليطاع"], 0, "ليطيعَنَّ (مبني على الفتح لاتصاله بنون التوكيد في جواب القسم)."],
    [369, "من خصائص الرسالة الشخصية والإخوانية الدقة العلمية والمصطلحات الجافة:", ["صح", "خطأ"], 1, "خطأ؛ هذه خصائص الرسائل الرسمية والعلمية."],
    [370, "كلمة (أمضى) تنتهي بألف لينة مقصورة:", ["صح", "خطأ"], 0, "صح (ألف لينة فوق ثلاثية كتبت ياء)."],
    [371, "علامة جر جمع المؤنث السالم هي:", ["الياء", "الباء", "الفتحة", "الكسرة"], 3, "الكسرة (علامة أصلية في الجر)."],
    [372, "علامة الترقيم التي تعبر عن الدهشة والاستغراب:", ["علامة التعجب (!)", "علامة الحذف", "الاستفهام", "النقطتان"], 0, "علامة التعجب والـتأثر."],
    [373, "(لَا أُقْسِمُ بِهَذَا الْبَلَدِ) إعراب (هذا):", ["اسم إشارة لا محل له", "في محل رفع", "في محل نصب", "اسم إشارة مبني في محل جر بحرف الجر"], 3, "مسبوق بالباء فهو في محل جر."],
    [374, "صورة الخبر في جملة (المؤمنُ خُلُقُهُ حَسَنٌ):", ["جملة فعلية", "جملة اسمية", "شبه جملة", "مفرد"], 1, "جملة اسمية من مبتدأ ثان وخبره."],
    [375, "الألف تكتب وتنطق في كلمة (مائة):", ["صح", "خطأ"], 1, "خطأ؛ تزاد الألف خطاً في مائة ولا تلفظ."],
    [376, "الاسمان (أسامة ومعاوية) علمان ممنوعان من الصرف لأنهما:", ["مذكران لفظاً", "مؤنثان تأنيثاً لفظياً", "أعجميان", "على وزن فعل"], 1, "علم لمذكر لحقته تاء التأنيث فيمنع للتأنيث اللفظي."],
    [377, "تشترك (التي، الذي، الذين) جميعاً في أنها:", ["أسماء شرط", "ضمائر متصلة", "ضمائر منفصلة", "أسماء موصولة مختصة"], 3, "أسماء موصولة خاصة ومختصة."],
    [378, "(نحن نصدق في القول والعمل) كلمة نحن تصنف:", ["ضميراً ظاهراً منفصلاً", "ضميراً مستتراً", "ضميراً متصلاً", "حرفاً"], 0, "ضمير منفصل للمتكلم المعظم نفسه أو الجمع."],
    [379, "كلمة (موسيقا) كتبت ألفها قائمة لأنها من الأسماء:", ["المبنية", "المعربة", "الموصولة", "الأعجمية"], 3, "الأسماء غير العربية والأعجمية تكتب ألفها قائمة."],
    [380, "زيدٌ كاتبٌ شاعرٌ. الكلمتان كاتب وشاعر تعربان:", ["خبر للمبتدأ", "خبران للمبتدأ", "الأولى خبر والثانية توكيد", "الأولى خبر والثانية بدل"], 1, "خبران متتابعان للمبتدأ."],
    [381, "(أفلح فاعلو الخير) حذفت النون من كلمة فاعلو بسبب:", ["الضمير الغائب", "الجزم", "وقوعها بعد ماض", "الإضافة إلى كلمة الخير"], 3, "تحذف نون الجمع والمثنى وجوباً عند الإضافة."]
  ];

  arList.forEach(item => {
    COURSES_DATA.ar111.questions.push({ id: item[0], q: item[1], opts: item[2], c: item[3], exp: item[4] });
  });

  // 2. استكمال بنك TU170 من الأسئلة 51 إلى 136
  const tuList = [
    [51, "A program must be loaded into ROM before it can run.", ["True", "False"], 1, "False; Programs must be loaded into RAM before execution."],
    [52, "What role does antispyware software play?", ["Identifies and removes unwanted spyware programs", "Protects against all physical threats", "Increases internet speed", "Manages data backups"], 0, "Antispyware detects and removes spyware."],
    [53, "One of the computer's functions is input, which saves data and information in the computer.", ["True", "False"], 1, "False; Input gathers data; storage saves it."],
    [54, "What is a characteristic of unshielded twisted-pair (UTP) cables?", ["They use glass fibers for transmission", "They don't include copper wires", "They are made of single copper wire surrounded by plastic", "They consist of twisted copper wires surrounded by plastic"], 3, "UTP cables consist of pairs of twisted copper wires."],
    [55, "The first type of portable computer was the:", ["Desktop", "Tablet", "Laptop", "Smartphone"], 2, "Laptops were the earliest portable personal computers."],
    [56, "You cannot connect a printer to a computer network.", ["True", "False"], 1, "False; Network printers can be shared across computers."],
    [57, "In a client/server architecture, clients:", ["Are responsible for primary data storage", "Request information or services from the server", "Manage the network infrastructure", "Provide services to other computers"], 1, "Clients make requests for services to a server."],
    [58, "Considering Bloom's Taxonomy, when you are able to make practical applications of learning, you have reached:", ["Understanding", "Remembering", "Applying", "Analyzing"], 2, "Applying involves using knowledge in concrete situations."],
    [59, "Which of the following is NOT recommended in your study space?", ["Choosing a quiet environment", "Using the space for multiple non-study activities", "Creating a regular study center", "Organizing files digitally"], 1, "Study spaces should be dedicated to studying and free from distractions."],
    [60, "Which of the following is a primary function of an operating system?", ["Allowing applications to interact with the CPU", "Managing tasks and scheduling processes", "Controlling peripheral hardware", "All answers are correct"], 3, "The OS coordinates all processor, memory, and device activities."],
    [61, "Which of the following is used to organize files on a computer storage drive?", ["Folder", "Program", "Browser", "Operating system"], 0, "Folders organize files hierarchically."],
    [62, "According to the course, what is the recommended strategy for answering questions in an exam?", ["Answer randomly to save time", "Skip all questions and come back later", "Start with the hardest questions first", "Answer the easy questions first"], 3, "Answering easy questions first builds confidence and saves time."],
    [63, "Business-to-consumer (B2C) transactions take place between businesses and consumers.", ["True", "False"], 0, "True; B2C transactions involve businesses selling to retail customers."],
    [64, "In Computer Literacy, not understanding how to diagnose and fix problems saves time and money.", ["True", "False"], 1, "False; Knowing how to fix basic issues saves time and repair fees."],
    [65, "Which of the following is a recognized type of hard disk?", ["External hard disk", "Universal hard disk", "Multi hard disk", "Global hard disk"], 0, "External hard disks connect externally via USB or Thunderbolt."],
    [66, "In the R.E.D. Model of critical thinking, what does 'D' stand for?", ["Draw Conclusions", "Draw facts", "Deliver assumptions", "Determine facts"], 0, "D stands for Draw Conclusions."],
    [67, "In the R.E.D. Model, what does 'R' stand for?", ["Recognize Assumptions", "Respond to facts", "Recognize Recommendations", "Recognize Results"], 0, "R stands for Recognize Assumptions."],
    [68, "In the R.E.D. Model, what does 'E' stand for?", ["Examine Ideas", "Evaluate Emotions", "Evaluate Information", "Evaluate Arguments / Evidence"], 3, "E stands for Evaluate Arguments / Evidence."],
    [69, "The circuit board that contains the central electronic components of the computer is the:", ["Input board", "Output board", "Motherboard", "Desktop board"], 2, "The motherboard is the main printed circuit board."],
    [70, "Critical thinking means making decisions based on assumptions.", ["True", "False"], 1, "False; Critical thinking questions assumptions and relies on verified evidence."],
    [71, "In the URL 'https://www.arabou.edu', which part represents the domain name?", ["edu", "https://www.arabou.edu", "www.arabou.edu", "arabou"], 2, "www.arabou.edu is the complete domain name."],
    [72, "In the URL 'https://www.arabou.edu', which part represents the protocol?", ["https", "https://www.arabou.edu", "www.arabou.edu", "edu"], 0, "https is the web protocol."],
    [73, "Which of the following is an example of a tablet computer?", ["Samsung smartphone", "Apple iPad", "HP gaming laptop", "Dell desktop PC"], 1, "Apple iPad is a tablet."],
    [74, "Dropbox is an example of:", ["File storage service", "Web browser", "Email address", "Searching engine"], 0, "Dropbox is a cloud file storage provider."],
    [75, "One petabyte (PB) = 1024 TB.", ["True", "False"], 0, "True; 1 PB = 1024 TB."],
    [76, "What is a recommended action for effective emergency studying?", ["Study everything without focus", "Ignore important materials", "Panic", "Relax and anticipate key questions"], 3, "Focus calmly on key high-probability questions."],
    [77, "Which storage device has NO spinning or moving parts?", ["DVDs", "CDs", "Solid-state storage devices (SSDs / USB)", "Hard disks"], 2, "SSDs and flash storage contain no mechanical spinning components."],
    [78, "Chromebook laptops feature:", ["All answers are correct", "Heavy computing hardware", "They use the Google Chrome OS", "They can convert into a tablet"], 2, "Chromebooks run Google Chrome OS."],
    [79, "In binary language, every letter on the keyboard is represented by one bit.", ["True", "False"], 1, "False; Each character is represented by 8 bits (1 byte)."],
    [80, "Which sensor in a phone detects when it is near your ear to turn off the screen during a call?", ["Pedometer sensor", "Proximity sensor", "Fingerprint sensor", "Magnetometer sensor"], 1, "The proximity sensor turns off the screen when against your ear."],
    [81, "Which sensor in a phone is used by compass apps?", ["Thermometer sensor", "Pedometer sensor", "Fingerprint sensor", "Magnetometer sensor"], 3, "The magnetometer acts as a compass."],
    [82, "Which sensor in a phone records the number of steps taken?", ["Pedometer sensor", "Fingerprint sensor", "Magnetometer sensor", "Thermometer sensor"], 0, "A pedometer tracks steps."],
    [83, "When evaluating a website's content, checking if the author has bias or is objective is part of:", ["Currency", "Authority", "Objectivity", "Accuracy"], 2, "Objectivity assesses whether content is neutral."],
    [84, "When evaluating website content, whether the information is up-to-date is part of:", ["Objectivity", "Accuracy", "Currency", "Authority"], 2, "Currency assesses timeliness and dates."],
    [85, "When evaluating website content, whether the author is an expert is part of:", ["Currency", "Authority", "Accuracy", "Objectivity"], 1, "Authority refers to credentials and expertise."],
    [86, "Which application of artificial intelligence helps in the design of prosthetic devices?", ["Facial recognition", "Law violation detection", "Machine learning", "3D printing"], 3, "3D printing enables custom prosthetic limbs."],
    [87, "Type of computers often used in insurance companies and banks to manage massive amounts of data:", ["Embedded Computers", "Supercomputer", "Both", "Mainframes"], 3, "Mainframes excel in enterprise data management."],
    [88, "The spider program is part of a search engine that:", ["Pulls out relevant information", "Organizes the database", "Searches index data", "Constantly collects data on the web (web crawler)"], 3, "Spiders continually crawl and index the web."],
    [89, "A printer that combines printing, scanning, and copying functions is an:", ["3D printer", "All-in-one printer (Multifunction)", "Large format printer", "Impact printer"], 1, "All-in-one printers combine print, scan, and copy."],
    [90, "If a solution doesn't work as expected, you should analyze what went wrong and try again.", ["True", "False"], 0, "True; Iterative reflection improves solutions."],
    [91, "When the computer is turned off, RAM loses all of its contents.", ["True", "False"], 0, "True; RAM is volatile."],
    [92, "When the computer is turned off, ROM loses all of its contents.", ["True", "False"], 1, "False; ROM is permanent (non-volatile)."],
    [93, "What is recommended if you feel test anxiety before an exam?", ["Blame others", "Visit a therapist immediately", "Encourage yourself like you would encourage a friend", "Ignore feelings"], 2, "Positive self-talk reduces test anxiety."],
    [94, "Which of the following output devices produces a hard copy of digital data?", ["Speakers", "Monitor", "Printer", "Projector"], 2, "Printers create physical hard copies."],
    [95, "To play a video game on a computer, you need:", ["Software only", "Hardware only", "Keyboard only", "Both software and hardware"], 3, "Both software and hardware are required."],
    [96, "The largest network in the world is the:", ["USB", "Facebook", "Internet", "Web"], 2, "The Internet is the global network."],
    [97, "Consumer-to-consumer (C2C) e-commerce occurs when consumers sell directly to other consumers (e.g., eBay).", ["True", "False"], 0, "True; C2C is consumer-to-consumer commerce."],
    [98, "RAM and ROM are two examples of temporary memories.", ["True", "False"], 1, "False; RAM is temporary, ROM is non-volatile."],
    [99, "The pen-like device used to draw or write on tablet screens is called a:", ["Stylus", "Virtual Keyboard", "Trackball", "Lightbar"], 0, "A stylus is a digital pen."],
    [100, "A laptop that can be converted into a tablet-like device is known as a:", ["Ultrabook", "Laptop", "2-in-1 PC", "Desktop"], 2, "2-in-1 PCs can convert into tablets."],
    [101, "One of the computer's functions is output, which manipulates and calculates data.", ["True", "False"], 1, "False; Processing manipulates data, while output displays results."],
    [102, "Supercomputer is the fastest type of computers in the world.", ["True", "False"], 0, "True; Supercomputers deliver the fastest compute speeds."],
    [103, "The Top-Level Domain of commercial websites is:", [".org", ".mil", ".com", ".edu"], 2, ".com is for commercial enterprises."],
    [104, "The Top-Level Domain of military websites is:", [".gov", ".mil", ".net", ".com"], 1, ".mil is for the military."],
    [105, "For browsers to connect to resources, the location must be specified via:", ["HTML", "Domain names", "TLDs", "Uniform Resource Locators (URLs)"], 3, "URLs provide the full resource locator."],
    [106, "Hospitals using 3D printing for:", ["Wasting money", "Diagnosing unfamiliar conditions", "Integrating patient systems", "Developing inexpensive and stylish prosthetic devices"], 3, "3D printing customizes affordable prosthetics."],
    [107, "When evaluating web content, whether the information is correct and critically reviewed refers to:", ["Currency", "Authority", "Accuracy", "Objectivity"], 2, "Accuracy refers to correctness and peer review."],
    [108, "The presence of a date indicating the last update on a website refers to:", ["Accuracy", "Currency", "Authority", "Objectivity"], 1, "Currency evaluates update timestamps."],
    [109, "How does starting to study early impact test anxiety?", ["Lowers anxiety and builds confidence", "Has no effect", "Increases anxiety", "Decreases performance"], 0, "Early preparation builds confidence."],
    [110, "Feeling stress or fear before or during an exam is called:", ["Performance Anxiety", "Test Anxiety", "General Anxiety", "Exam Depression"], 1, "Test anxiety."],
    [111, "If you do not prepare yourself for an exam, this leads to:", ["Feeling test anxiety", "Feeling relaxed", "Feeling confident", "Feeling happy"], 0, "Unpreparedness induces test anxiety."],
    [112, "To protect transactions in online shopping, it is NOT good to use a third-party payer (e.g., PayPal).", ["True", "False"], 1, "False; Third-party payers provide extra security."],
    [113, "Internal hard disks are located outside the system unit.", ["True", "False"], 1, "False; Internal hard disks reside inside the system chassis."],
    [114, "Apple MacBook Air is classified as a/an:", ["Desktop", "Laptop / Ultrabook", "2-in-1 PC", "Chromebook"], 1, "Ultrabook/thin laptop."],
    [115, "The motherboard is located inside the:", ["Smartboard", "System unit", "Memory board", "Monitor"], 1, "The system unit chassis."],
    [116, "The two digits used in binary language are:", ["0 and 8", "0 and 2", "0 and 1", "1 and 2"], 2, "Binary uses 0 and 1."],
    [117, "Why are smartphones considered computers?", ["They have a screen", "They connect to internet", "They make calls", "They have processing power, memory, input and output"], 3, "Smartphones contain all fundamental computing hardware."],
    [118, "Which of the following is the default web browser in Windows 10/11?", ["Microsoft Edge", "Safari", "Firefox", "Google Chrome"], 0, "Microsoft Edge is the default Windows browser."],
    [119, "The 's' in 'https://' indicates that the website is secure.", ["True", "False"], 0, "True; 's' stands for Secure (SSL/TLS)."],
    [120, "Cloud computing Back End refers to:", ["The user-facing side", "Web browsers", "Data centers and server farms globally", "Local storage"], 2, "Back End consists of servers, databases, and data centers."],
    [121, "Robots in industrial manufacturing primarily perform:", ["Customer service", "Repetitive tasks", "Creative tasks", "Cooking"], 1, "Industrial robots excel at repetitive, hazardous tasks."],
    [122, "1024 Gigabytes (GB) are equal to:", ["1 Terabyte (TB)", "1 Megabyte (MB)", "1 Petabyte (PB)", "1 Kilobyte (KB)"], 0, "1024 GB = 1 TB."],
    [123, "1024 Bytes is larger than 1 Megabyte (MB).", ["True", "False"], 1, "False; 1 MB = 1,048,576 Bytes."],
    [124, "The physical components of the computer you can touch are:", ["Hardware", "Software", "Programs", "Data"], 0, "Hardware."],
    [125, "Which factor directly determines CPU performance?", ["Number of cores and clock speed", "Sensor quality", "Internet speed", "Screen resolution"], 0, "Number of cores and clock frequency."],
    [126, "Cheating on an exam is considered:", ["Good behavior", "Unethical behavior", "Ethical behavior", "Standard experience"], 1, "Unethical behavior."],
    [127, "A printer that generates oversized images such as blueprints and banners is a:", ["3D printer", "All-in-one printer", "Large format printer (Plotter)", "Laser printer"], 2, "Large format printer."],
    [128, "Dropping a class because it introduces unfamiliar tools instead of trying is:", ["Quitting from the situation", "Adapting old skills", "Modifying skills", "Staying without adjusting"], 0, "Quitting from the situation."],
    [129, "A Microphone is an example of a/an:", ["Audio-input device", "Image capture device", "Pointing device", "Output device"], 0, "Audio-input device."],
    [130, "What is confirmation bias?", ["Forgetting easily", "Seeking and favoring information that supports pre-existing beliefs", "Neutral analysis", "Questioning everything"], 1, "Favoring information matching existing beliefs."],
    [131, "Digital convergence is illustrated by smartphones combining GPS, camera, and calling.", ["True", "False"], 0, "True; Convergence merges multiple technologies into one device."],
    [132, "It is safe to conduct online financial transactions from public computers.", ["True", "False"], 1, "False; Public computers pose risks of keyloggers and malware."],
    [133, "Which of the following is NOT protected as intellectual property?", ["Software source code", "Political opinions", "Paintings", "Music tracks"], 1, "General opinions cannot be copyrighted."],
    [134, "When should you arrive for an examination?", ["Exactly when it begins", "Whenever you like", "Late", "Early to prepare calmly"], 3, "Arriving early reduces stress."],
    [135, "Computer literacy helps users to avoid Spam, Adware, and Spyware.", ["True", "False"], 0, "True; Literacy fosters safe online habits."],
    [136, "What is the primary role of the CPU in a computer?", ["Display graphics", "Store documents permanently", "Control and process all instructions from software", "Supply electrical power"], 2, "Execute software instructions and manage processing."]
  ];

  tuList.forEach(item => {
    COURSES_DATA.tu170.questions.push({ id: item[0], q: item[1], opts: item[2], c: item[3], exp: item[4] });
  });
})();
